/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { InvoicingV2InvoiceSettingsGet200Response } from '../models';
import { InvoicingV2InvoiceSettingsGet400Response } from '../models';
import { InvoicingV2InvoiceSettingsGet502Response } from '../models';
import { InvoicingV2InvoiceSettingsPut200Response } from '../models';
import { InvoicingV2InvoiceSettingsPut400Response } from '../models';
import { InvoicingV2InvoiceSettingsPut502Response } from '../models';
import { V2InvoiceSettingsBody } from '../models';
/**
 * InvoiceSettingsApi - axios parameter creator
 * @export
 */
export const InvoiceSettingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get the invoice settings for the invoice payment page.
         * @summary Get Invoice Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInvoiceSettings: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/invoicing/v2/invoiceSettings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Update invoice settings for the invoice payment page.
         * @summary Update Invoice Settings
         * @param {V2InvoiceSettingsBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInvoiceSettings: async (body: V2InvoiceSettingsBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateInvoiceSettings.');
            }
            const localVarPath = `/invoicing/v2/invoiceSettings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json;charset=utf-8';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvoiceSettingsApi - functional programming interface
 * @export
 */
export const InvoiceSettingsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get the invoice settings for the invoice payment page.
         * @summary Get Invoice Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInvoiceSettings(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InvoicingV2InvoiceSettingsGet200Response>>> {
            const localVarAxiosArgs = await InvoiceSettingsApiAxiosParamCreator(configuration).getInvoiceSettings(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Update invoice settings for the invoice payment page.
         * @summary Update Invoice Settings
         * @param {V2InvoiceSettingsBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateInvoiceSettings(body: V2InvoiceSettingsBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InvoicingV2InvoiceSettingsPut200Response>>> {
            const localVarAxiosArgs = await InvoiceSettingsApiAxiosParamCreator(configuration).updateInvoiceSettings(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * InvoiceSettingsApi - factory interface
 * @export
 */
export const InvoiceSettingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get the invoice settings for the invoice payment page.
         * @summary Get Invoice Settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInvoiceSettings(options?: AxiosRequestConfig): Promise<AxiosResponse<InvoicingV2InvoiceSettingsGet200Response>> {
            return InvoiceSettingsApiFp(configuration).getInvoiceSettings(options).then((request) => request(axios, basePath));
        },
        /**
         * Update invoice settings for the invoice payment page.
         * @summary Update Invoice Settings
         * @param {V2InvoiceSettingsBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateInvoiceSettings(body: V2InvoiceSettingsBody, options?: AxiosRequestConfig): Promise<AxiosResponse<InvoicingV2InvoiceSettingsPut200Response>> {
            return InvoiceSettingsApiFp(configuration).updateInvoiceSettings(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InvoiceSettingsApi - object-oriented interface
 * @export
 * @class InvoiceSettingsApi
 * @extends {BaseAPI}
 */
export class InvoiceSettingsApi extends BaseAPI {
    /**
     * Get the invoice settings for the invoice payment page.
     * @summary Get Invoice Settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoiceSettingsApi
     */
    public async getInvoiceSettings(options?: AxiosRequestConfig) : Promise<AxiosResponse<InvoicingV2InvoiceSettingsGet200Response>> {
        return InvoiceSettingsApiFp(this.configuration).getInvoiceSettings(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Update invoice settings for the invoice payment page.
     * @summary Update Invoice Settings
     * @param {V2InvoiceSettingsBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InvoiceSettingsApi
     */
    public async updateInvoiceSettings(body: V2InvoiceSettingsBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<InvoicingV2InvoiceSettingsPut200Response>> {
        return InvoiceSettingsApiFp(this.configuration).updateInvoiceSettings(body, options).then((request) => request(this.axios, this.basePath));
    }
}
