/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { TaxIdBody } from '../models';
import { V2TaxBody } from '../models';
import { VasV2PaymentsPost201Response } from '../models';
import { VasV2PaymentsPost400Response } from '../models';
import { VasV2PaymentsPost502Response } from '../models';
import { VasV2TaxVoid200Response } from '../models';
import { VasV2TaxVoidsPost400Response } from '../models';
import { VasV2TaxVoidsPost502Response } from '../models';
/**
 * TaxesApi - axios parameter creator
 * @export
 */
export const TaxesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get tax details for a transaction. 
         * @summary Calculate Taxes
         * @param {V2TaxBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calculateTax: async (body: V2TaxBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling calculateTax.');
            }
            const localVarPath = `/vas/v2/tax`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json;charset=utf-8';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Pass the Tax Request ID in the PATCH request to void the committed tax calculation.
         * @summary Void Taxes
         * @param {TaxIdBody} body 
         * @param {string} id The tax ID returned from a previous request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        voidTax: async (body: TaxIdBody, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling voidTax.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling voidTax.');
            }
            const localVarPath = `/vas/v2/tax/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json;charset=utf-8';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TaxesApi - functional programming interface
 * @export
 */
export const TaxesApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get tax details for a transaction. 
         * @summary Calculate Taxes
         * @param {V2TaxBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calculateTax(body: V2TaxBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VasV2PaymentsPost201Response>>> {
            const localVarAxiosArgs = await TaxesApiAxiosParamCreator(configuration).calculateTax(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Pass the Tax Request ID in the PATCH request to void the committed tax calculation.
         * @summary Void Taxes
         * @param {TaxIdBody} body 
         * @param {string} id The tax ID returned from a previous request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voidTax(body: TaxIdBody, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VasV2TaxVoid200Response>>> {
            const localVarAxiosArgs = await TaxesApiAxiosParamCreator(configuration).voidTax(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TaxesApi - factory interface
 * @export
 */
export const TaxesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get tax details for a transaction. 
         * @summary Calculate Taxes
         * @param {V2TaxBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calculateTax(body: V2TaxBody, options?: AxiosRequestConfig): Promise<AxiosResponse<VasV2PaymentsPost201Response>> {
            return TaxesApiFp(configuration).calculateTax(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Pass the Tax Request ID in the PATCH request to void the committed tax calculation.
         * @summary Void Taxes
         * @param {TaxIdBody} body 
         * @param {string} id The tax ID returned from a previous request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voidTax(body: TaxIdBody, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<VasV2TaxVoid200Response>> {
            return TaxesApiFp(configuration).voidTax(body, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TaxesApi - object-oriented interface
 * @export
 * @class TaxesApi
 * @extends {BaseAPI}
 */
export class TaxesApi extends BaseAPI {
    /**
     * Get tax details for a transaction. 
     * @summary Calculate Taxes
     * @param {V2TaxBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxesApi
     */
    public async calculateTax(body: V2TaxBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<VasV2PaymentsPost201Response>> {
        return TaxesApiFp(this.configuration).calculateTax(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Pass the Tax Request ID in the PATCH request to void the committed tax calculation.
     * @summary Void Taxes
     * @param {TaxIdBody} body 
     * @param {string} id The tax ID returned from a previous request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaxesApi
     */
    public async voidTax(body: TaxIdBody, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<VasV2TaxVoid200Response>> {
        return TaxesApiFp(this.configuration).voidTax(body, id, options).then((request) => request(this.axios, this.basePath));
    }
}
