/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { TssV2TransactionsGet200Response } from '../models';
/**
 * TransactionDetailsApi - axios parameter creator
 * @export
 */
export const TransactionDetailsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Include the Request ID in the GET request to retrieve the transaction details.
         * @summary Retrieve a Transaction
         * @param {string} id Request ID. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransaction: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getTransaction.');
            }
            const localVarPath = `/tss/v2/transactions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication jwt required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionDetailsApi - functional programming interface
 * @export
 */
export const TransactionDetailsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Include the Request ID in the GET request to retrieve the transaction details.
         * @summary Retrieve a Transaction
         * @param {string} id Request ID. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTransaction(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TssV2TransactionsGet200Response>>> {
            const localVarAxiosArgs = await TransactionDetailsApiAxiosParamCreator(configuration).getTransaction(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TransactionDetailsApi - factory interface
 * @export
 */
export const TransactionDetailsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Include the Request ID in the GET request to retrieve the transaction details.
         * @summary Retrieve a Transaction
         * @param {string} id Request ID. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTransaction(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TssV2TransactionsGet200Response>> {
            return TransactionDetailsApiFp(configuration).getTransaction(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TransactionDetailsApi - object-oriented interface
 * @export
 * @class TransactionDetailsApi
 * @extends {BaseAPI}
 */
export class TransactionDetailsApi extends BaseAPI {
    /**
     * Include the Request ID in the GET request to retrieve the transaction details.
     * @summary Retrieve a Transaction
     * @param {string} id Request ID. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionDetailsApi
     */
    public async getTransaction(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TssV2TransactionsGet200Response>> {
        return TransactionDetailsApiFp(this.configuration).getTransaction(id, options).then((request) => request(this.axios, this.basePath));
    }
}
