/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { UmsV1UsersGet200Response } from '../models';
import { UmsV1UsersGet400Response } from '../models';
/**
 * UserManagementApi - axios parameter creator
 * @export
 */
export const UserManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This endpoint is deprecated. Please use the search end point.
         * @summary Get User Information - Deprecated
         * @param {string} [organizationId] This is the orgId of the organization which the user belongs to.
         * @param {string} [userName] User ID of the user you want to get details on.
         * @param {string} [permissionId] permission that you are trying to search user on.
         * @param {string} [roleId] role of the user you are trying to search on.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers: async (organizationId?: string, userName?: string, permissionId?: string, roleId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ums/v1/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (organizationId !== undefined) {
                localVarQueryParameter['organizationId'] = organizationId;
            }

            if (userName !== undefined) {
                localVarQueryParameter['userName'] = userName;
            }

            if (permissionId !== undefined) {
                localVarQueryParameter['permissionId'] = permissionId;
            }

            if (roleId !== undefined) {
                localVarQueryParameter['roleId'] = roleId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserManagementApi - functional programming interface
 * @export
 */
export const UserManagementApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This endpoint is deprecated. Please use the search end point.
         * @summary Get User Information - Deprecated
         * @param {string} [organizationId] This is the orgId of the organization which the user belongs to.
         * @param {string} [userName] User ID of the user you want to get details on.
         * @param {string} [permissionId] permission that you are trying to search user on.
         * @param {string} [roleId] role of the user you are trying to search on.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUsers(organizationId?: string, userName?: string, permissionId?: string, roleId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UmsV1UsersGet200Response>>> {
            const localVarAxiosArgs = await UserManagementApiAxiosParamCreator(configuration).getUsers(organizationId, userName, permissionId, roleId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UserManagementApi - factory interface
 * @export
 */
export const UserManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * This endpoint is deprecated. Please use the search end point.
         * @summary Get User Information - Deprecated
         * @param {string} [organizationId] This is the orgId of the organization which the user belongs to.
         * @param {string} [userName] User ID of the user you want to get details on.
         * @param {string} [permissionId] permission that you are trying to search user on.
         * @param {string} [roleId] role of the user you are trying to search on.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUsers(organizationId?: string, userName?: string, permissionId?: string, roleId?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<UmsV1UsersGet200Response>> {
            return UserManagementApiFp(configuration).getUsers(organizationId, userName, permissionId, roleId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserManagementApi - object-oriented interface
 * @export
 * @class UserManagementApi
 * @extends {BaseAPI}
 */
export class UserManagementApi extends BaseAPI {
    /**
     * This endpoint is deprecated. Please use the search end point.
     * @summary Get User Information - Deprecated
     * @param {string} [organizationId] This is the orgId of the organization which the user belongs to.
     * @param {string} [userName] User ID of the user you want to get details on.
     * @param {string} [permissionId] permission that you are trying to search user on.
     * @param {string} [roleId] role of the user you are trying to search on.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserManagementApi
     */
    public async getUsers(organizationId?: string, userName?: string, permissionId?: string, roleId?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<UmsV1UsersGet200Response>> {
        return UserManagementApiFp(this.configuration).getUsers(organizationId, userName, permissionId, roleId, options).then((request) => request(this.axios, this.basePath));
    }
}
