/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { IdVoidsBody } from '../models';
import { IdVoidsBody1 } from '../models';
import { IdVoidsBody2 } from '../models';
import { IdVoidsBody3 } from '../models';
import { PtsV2CapturesVoidsPost201Response } from '../models';
import { PtsV2CapturesVoidsPost400Response } from '../models';
import { PtsV2CapturesVoidsPost502Response } from '../models';
import { PtsV2CreditsVoidsPost201Response } from '../models';
import { PtsV2CreditsVoidsPost400Response } from '../models';
import { PtsV2CreditsVoidsPost502Response } from '../models';
import { PtsV2PaymentsVoidsPost201Response } from '../models';
import { PtsV2PaymentsVoidsPost400Response } from '../models';
import { PtsV2PaymentsVoidsPost502Response } from '../models';
import { PtsV2RefundsVoidsPost201Response } from '../models';
import { PtsV2RefundsVoidsPost400Response } from '../models';
import { PtsV2RefundsVoidsPost502Response } from '../models';
import { PtsV2VoidsPost200Response } from '../models';
import { PtsV2VoidsPost400Response } from '../models';
import { PtsV2VoidsPost502Response } from '../models';
import { V2VoidsBody } from '../models';
/**
 * VoidApi - axios parameter creator
 * @export
 */
export const VoidApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This is to void a previous payment, capture, refund, or credit that merchant does not receive a reply(Mostly due to timeout). This is to void a previous payment, capture, refund, or credit that merchant does not receive a reply(Mostly due to Timeout). To use this feature/API, make sure to pass unique value to field - clientReferenceInformation -> transactionId in your payment, capture, refund, or credit API call and use same transactionId in this API request payload to reverse the payment.
         * @summary Timeout Void
         * @param {V2VoidsBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mitVoid: async (body: V2VoidsBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling mitVoid.');
            }
            const localVarPath = `/pts/v2/voids/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json;charset=utf-8';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Refund a capture API is only used, if you have requested Capture independenlty using [/pts/v2/payments/{id}/captures](https://developer.cybersource.com/api-reference-assets/index.html#payments_capture) API call. Include the capture ID in the POST request to cancel the capture. 
         * @summary Void a Capture
         * @param {IdVoidsBody1} body 
         * @param {string} id The capture ID returned from a previous capture request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        voidCapture: async (body: IdVoidsBody1, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling voidCapture.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling voidCapture.');
            }
            const localVarPath = `/pts/v2/captures/{id}/voids`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json;charset=utf-8';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Include the credit ID in the POST request to cancel the credit.
         * @summary Void a Credit
         * @param {IdVoidsBody3} body 
         * @param {string} id The credit ID returned from a previous credit request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        voidCredit: async (body: IdVoidsBody3, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling voidCredit.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling voidCredit.');
            }
            const localVarPath = `/pts/v2/credits/{id}/voids`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json;charset=utf-8';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Void a Payment API is only used, if you have requested Authorization and Capture together in [/pts/v2/payments](https://developer.cybersource.com/api-reference-assets/index.html#payments_payments) API call. Include the payment ID in the POST request to cancel the payment. 
         * @summary Void a Payment
         * @param {IdVoidsBody} body 
         * @param {string} id The payment ID returned from a previous payment request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        voidPayment: async (body: IdVoidsBody, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling voidPayment.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling voidPayment.');
            }
            const localVarPath = `/pts/v2/payments/{id}/voids`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json;charset=utf-8';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Include the refund ID in the POST request to cancel the refund.
         * @summary Void a Refund
         * @param {IdVoidsBody2} body 
         * @param {string} id The refund ID returned from a previous refund request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        voidRefund: async (body: IdVoidsBody2, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling voidRefund.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling voidRefund.');
            }
            const localVarPath = `/pts/v2/refunds/{id}/voids`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json;charset=utf-8';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VoidApi - functional programming interface
 * @export
 */
export const VoidApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This is to void a previous payment, capture, refund, or credit that merchant does not receive a reply(Mostly due to timeout). This is to void a previous payment, capture, refund, or credit that merchant does not receive a reply(Mostly due to Timeout). To use this feature/API, make sure to pass unique value to field - clientReferenceInformation -> transactionId in your payment, capture, refund, or credit API call and use same transactionId in this API request payload to reverse the payment.
         * @summary Timeout Void
         * @param {V2VoidsBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mitVoid(body: V2VoidsBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PtsV2VoidsPost200Response>>> {
            const localVarAxiosArgs = await VoidApiAxiosParamCreator(configuration).mitVoid(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Refund a capture API is only used, if you have requested Capture independenlty using [/pts/v2/payments/{id}/captures](https://developer.cybersource.com/api-reference-assets/index.html#payments_capture) API call. Include the capture ID in the POST request to cancel the capture. 
         * @summary Void a Capture
         * @param {IdVoidsBody1} body 
         * @param {string} id The capture ID returned from a previous capture request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voidCapture(body: IdVoidsBody1, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PtsV2CapturesVoidsPost201Response>>> {
            const localVarAxiosArgs = await VoidApiAxiosParamCreator(configuration).voidCapture(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Include the credit ID in the POST request to cancel the credit.
         * @summary Void a Credit
         * @param {IdVoidsBody3} body 
         * @param {string} id The credit ID returned from a previous credit request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voidCredit(body: IdVoidsBody3, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PtsV2CreditsVoidsPost201Response>>> {
            const localVarAxiosArgs = await VoidApiAxiosParamCreator(configuration).voidCredit(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Void a Payment API is only used, if you have requested Authorization and Capture together in [/pts/v2/payments](https://developer.cybersource.com/api-reference-assets/index.html#payments_payments) API call. Include the payment ID in the POST request to cancel the payment. 
         * @summary Void a Payment
         * @param {IdVoidsBody} body 
         * @param {string} id The payment ID returned from a previous payment request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voidPayment(body: IdVoidsBody, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PtsV2PaymentsVoidsPost201Response>>> {
            const localVarAxiosArgs = await VoidApiAxiosParamCreator(configuration).voidPayment(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Include the refund ID in the POST request to cancel the refund.
         * @summary Void a Refund
         * @param {IdVoidsBody2} body 
         * @param {string} id The refund ID returned from a previous refund request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voidRefund(body: IdVoidsBody2, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PtsV2RefundsVoidsPost201Response>>> {
            const localVarAxiosArgs = await VoidApiAxiosParamCreator(configuration).voidRefund(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * VoidApi - factory interface
 * @export
 */
export const VoidApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * This is to void a previous payment, capture, refund, or credit that merchant does not receive a reply(Mostly due to timeout). This is to void a previous payment, capture, refund, or credit that merchant does not receive a reply(Mostly due to Timeout). To use this feature/API, make sure to pass unique value to field - clientReferenceInformation -> transactionId in your payment, capture, refund, or credit API call and use same transactionId in this API request payload to reverse the payment.
         * @summary Timeout Void
         * @param {V2VoidsBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mitVoid(body: V2VoidsBody, options?: AxiosRequestConfig): Promise<AxiosResponse<PtsV2VoidsPost200Response>> {
            return VoidApiFp(configuration).mitVoid(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Refund a capture API is only used, if you have requested Capture independenlty using [/pts/v2/payments/{id}/captures](https://developer.cybersource.com/api-reference-assets/index.html#payments_capture) API call. Include the capture ID in the POST request to cancel the capture. 
         * @summary Void a Capture
         * @param {IdVoidsBody1} body 
         * @param {string} id The capture ID returned from a previous capture request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voidCapture(body: IdVoidsBody1, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<PtsV2CapturesVoidsPost201Response>> {
            return VoidApiFp(configuration).voidCapture(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * Include the credit ID in the POST request to cancel the credit.
         * @summary Void a Credit
         * @param {IdVoidsBody3} body 
         * @param {string} id The credit ID returned from a previous credit request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voidCredit(body: IdVoidsBody3, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<PtsV2CreditsVoidsPost201Response>> {
            return VoidApiFp(configuration).voidCredit(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * Void a Payment API is only used, if you have requested Authorization and Capture together in [/pts/v2/payments](https://developer.cybersource.com/api-reference-assets/index.html#payments_payments) API call. Include the payment ID in the POST request to cancel the payment. 
         * @summary Void a Payment
         * @param {IdVoidsBody} body 
         * @param {string} id The payment ID returned from a previous payment request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voidPayment(body: IdVoidsBody, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<PtsV2PaymentsVoidsPost201Response>> {
            return VoidApiFp(configuration).voidPayment(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * Include the refund ID in the POST request to cancel the refund.
         * @summary Void a Refund
         * @param {IdVoidsBody2} body 
         * @param {string} id The refund ID returned from a previous refund request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async voidRefund(body: IdVoidsBody2, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<PtsV2RefundsVoidsPost201Response>> {
            return VoidApiFp(configuration).voidRefund(body, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VoidApi - object-oriented interface
 * @export
 * @class VoidApi
 * @extends {BaseAPI}
 */
export class VoidApi extends BaseAPI {
    /**
     * This is to void a previous payment, capture, refund, or credit that merchant does not receive a reply(Mostly due to timeout). This is to void a previous payment, capture, refund, or credit that merchant does not receive a reply(Mostly due to Timeout). To use this feature/API, make sure to pass unique value to field - clientReferenceInformation -> transactionId in your payment, capture, refund, or credit API call and use same transactionId in this API request payload to reverse the payment.
     * @summary Timeout Void
     * @param {V2VoidsBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidApi
     */
    public async mitVoid(body: V2VoidsBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<PtsV2VoidsPost200Response>> {
        return VoidApiFp(this.configuration).mitVoid(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Refund a capture API is only used, if you have requested Capture independenlty using [/pts/v2/payments/{id}/captures](https://developer.cybersource.com/api-reference-assets/index.html#payments_capture) API call. Include the capture ID in the POST request to cancel the capture. 
     * @summary Void a Capture
     * @param {IdVoidsBody1} body 
     * @param {string} id The capture ID returned from a previous capture request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidApi
     */
    public async voidCapture(body: IdVoidsBody1, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<PtsV2CapturesVoidsPost201Response>> {
        return VoidApiFp(this.configuration).voidCapture(body, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Include the credit ID in the POST request to cancel the credit.
     * @summary Void a Credit
     * @param {IdVoidsBody3} body 
     * @param {string} id The credit ID returned from a previous credit request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidApi
     */
    public async voidCredit(body: IdVoidsBody3, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<PtsV2CreditsVoidsPost201Response>> {
        return VoidApiFp(this.configuration).voidCredit(body, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Void a Payment API is only used, if you have requested Authorization and Capture together in [/pts/v2/payments](https://developer.cybersource.com/api-reference-assets/index.html#payments_payments) API call. Include the payment ID in the POST request to cancel the payment. 
     * @summary Void a Payment
     * @param {IdVoidsBody} body 
     * @param {string} id The payment ID returned from a previous payment request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidApi
     */
    public async voidPayment(body: IdVoidsBody, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<PtsV2PaymentsVoidsPost201Response>> {
        return VoidApiFp(this.configuration).voidPayment(body, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Include the refund ID in the POST request to cancel the refund.
     * @summary Void a Refund
     * @param {IdVoidsBody2} body 
     * @param {string} id The refund ID returned from a previous refund request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VoidApi
     */
    public async voidRefund(body: IdVoidsBody2, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<PtsV2RefundsVoidsPost201Response>> {
        return VoidApiFp(this.configuration).voidRefund(body, id, options).then((request) => request(this.axios, this.basePath));
    }
}
