/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Tmsv2customersEmbeddedDefaultPaymentInstrumentBankAccount } from './tmsv2customers-embedded-default-payment-instrument-bank-account';
import { Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo } from './tmsv2customers-embedded-default-payment-instrument-bill-to';
import { Tmsv2customersEmbeddedDefaultPaymentInstrumentBuyerInformation } from './tmsv2customers-embedded-default-payment-instrument-buyer-information';
import { Tmsv2customersEmbeddedDefaultPaymentInstrumentCard } from './tmsv2customers-embedded-default-payment-instrument-card';
import { Tmsv2customersEmbeddedDefaultPaymentInstrumentEmbedded } from './tmsv2customers-embedded-default-payment-instrument-embedded';
import { Tmsv2customersEmbeddedDefaultPaymentInstrumentInstrumentIdentifier } from './tmsv2customers-embedded-default-payment-instrument-instrument-identifier';
import { Tmsv2customersEmbeddedDefaultPaymentInstrumentLinks } from './tmsv2customers-embedded-default-payment-instrument-links';
import { Tmsv2customersEmbeddedDefaultPaymentInstrumentMerchantInformation } from './tmsv2customers-embedded-default-payment-instrument-merchant-information';
import { Tmsv2customersEmbeddedDefaultPaymentInstrumentMetadata } from './tmsv2customers-embedded-default-payment-instrument-metadata';
import { Tmsv2customersEmbeddedDefaultPaymentInstrumentProcessingInformation } from './tmsv2customers-embedded-default-payment-instrument-processing-information';
/**
 * 
 * @export
 * @interface CustomerTokenIdPaymentinstrumentsBody
 */
export interface CustomerTokenIdPaymentinstrumentsBody {
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultPaymentInstrumentLinks}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    links?: Tmsv2customersEmbeddedDefaultPaymentInstrumentLinks;
    /**
     * The id of the Payment Instrument Token.
     * @type {string}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    id?: string;
    /**
     * The type of token.  Valid values: - paymentInstrument 
     * @type {string}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    object?: string;
    /**
     * Flag that indicates whether customer payment instrument is the dafault. Valid values:  - `true`: Payment instrument is customer's default.  - `false`: Payment instrument is not customer's default. 
     * @type {boolean}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    _default?: boolean;
    /**
     * Issuers state for the card number. Valid values: - ACTIVE - CLOSED : The account has been closed. 
     * @type {string}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    state?: string;
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultPaymentInstrumentBankAccount}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    bankAccount?: Tmsv2customersEmbeddedDefaultPaymentInstrumentBankAccount;
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultPaymentInstrumentCard}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    card?: Tmsv2customersEmbeddedDefaultPaymentInstrumentCard;
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultPaymentInstrumentBuyerInformation}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    buyerInformation?: Tmsv2customersEmbeddedDefaultPaymentInstrumentBuyerInformation;
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    billTo?: Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo;
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultPaymentInstrumentProcessingInformation}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    processingInformation?: Tmsv2customersEmbeddedDefaultPaymentInstrumentProcessingInformation;
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultPaymentInstrumentMerchantInformation}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    merchantInformation?: Tmsv2customersEmbeddedDefaultPaymentInstrumentMerchantInformation;
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultPaymentInstrumentInstrumentIdentifier}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    instrumentIdentifier?: Tmsv2customersEmbeddedDefaultPaymentInstrumentInstrumentIdentifier;
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultPaymentInstrumentMetadata}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    metadata?: Tmsv2customersEmbeddedDefaultPaymentInstrumentMetadata;
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultPaymentInstrumentEmbedded}
     * @memberof CustomerTokenIdPaymentinstrumentsBody
     */
    embedded?: Tmsv2customersEmbeddedDefaultPaymentInstrumentEmbedded;
}
