/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ptsv2paymentsClientReferenceInformation } from './ptsv2payments-client-reference-information';
import { Ptsv2paymentsMerchantDefinedInformation } from './ptsv2payments-merchant-defined-information';
import { Ptsv2paymentsPromotionInformation } from './ptsv2payments-promotion-information';
import { Ptsv2paymentsTravelInformation } from './ptsv2payments-travel-information';
import { Ptsv2paymentsidcapturesAggregatorInformation } from './ptsv2paymentsidcaptures-aggregator-information';
import { Ptsv2paymentsidcapturesBuyerInformation } from './ptsv2paymentsidcaptures-buyer-information';
import { Ptsv2paymentsidcapturesDeviceInformation } from './ptsv2paymentsidcaptures-device-information';
import { Ptsv2paymentsidcapturesInstallmentInformation } from './ptsv2paymentsidcaptures-installment-information';
import { Ptsv2paymentsidcapturesMerchantInformation } from './ptsv2paymentsidcaptures-merchant-information';
import { Ptsv2paymentsidcapturesOrderInformation } from './ptsv2paymentsidcaptures-order-information';
import { Ptsv2paymentsidcapturesPaymentInformation } from './ptsv2paymentsidcaptures-payment-information';
import { Ptsv2paymentsidcapturesPointOfSaleInformation } from './ptsv2paymentsidcaptures-point-of-sale-information';
import { Ptsv2paymentsidcapturesProcessingInformation } from './ptsv2paymentsidcaptures-processing-information';
/**
 * 
 * @export
 * @interface IdCapturesBody
 */
export interface IdCapturesBody {
    /**
     * 
     * @type {Ptsv2paymentsClientReferenceInformation}
     * @memberof IdCapturesBody
     */
    clientReferenceInformation?: Ptsv2paymentsClientReferenceInformation;
    /**
     * 
     * @type {Ptsv2paymentsidcapturesProcessingInformation}
     * @memberof IdCapturesBody
     */
    processingInformation?: Ptsv2paymentsidcapturesProcessingInformation;
    /**
     * 
     * @type {Ptsv2paymentsidcapturesPaymentInformation}
     * @memberof IdCapturesBody
     */
    paymentInformation?: Ptsv2paymentsidcapturesPaymentInformation;
    /**
     * 
     * @type {Ptsv2paymentsidcapturesOrderInformation}
     * @memberof IdCapturesBody
     */
    orderInformation?: Ptsv2paymentsidcapturesOrderInformation;
    /**
     * 
     * @type {Ptsv2paymentsidcapturesBuyerInformation}
     * @memberof IdCapturesBody
     */
    buyerInformation?: Ptsv2paymentsidcapturesBuyerInformation;
    /**
     * 
     * @type {Ptsv2paymentsidcapturesDeviceInformation}
     * @memberof IdCapturesBody
     */
    deviceInformation?: Ptsv2paymentsidcapturesDeviceInformation;
    /**
     * 
     * @type {Ptsv2paymentsidcapturesMerchantInformation}
     * @memberof IdCapturesBody
     */
    merchantInformation?: Ptsv2paymentsidcapturesMerchantInformation;
    /**
     * 
     * @type {Ptsv2paymentsidcapturesAggregatorInformation}
     * @memberof IdCapturesBody
     */
    aggregatorInformation?: Ptsv2paymentsidcapturesAggregatorInformation;
    /**
     * 
     * @type {Ptsv2paymentsidcapturesPointOfSaleInformation}
     * @memberof IdCapturesBody
     */
    pointOfSaleInformation?: Ptsv2paymentsidcapturesPointOfSaleInformation;
    /**
     * The object containing the custom data that the merchant defines. 
     * @type {Array<Ptsv2paymentsMerchantDefinedInformation>}
     * @memberof IdCapturesBody
     */
    merchantDefinedInformation?: Array<Ptsv2paymentsMerchantDefinedInformation>;
    /**
     * 
     * @type {Ptsv2paymentsidcapturesInstallmentInformation}
     * @memberof IdCapturesBody
     */
    installmentInformation?: Ptsv2paymentsidcapturesInstallmentInformation;
    /**
     * 
     * @type {Ptsv2paymentsTravelInformation}
     * @memberof IdCapturesBody
     */
    travelInformation?: Ptsv2paymentsTravelInformation;
    /**
     * 
     * @type {Ptsv2paymentsPromotionInformation}
     * @memberof IdCapturesBody
     */
    promotionInformation?: Ptsv2paymentsPromotionInformation;
}
