/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Provide validation failed input field details
 * @export
 * @interface InlineResponse4001Fields
 */
export interface InlineResponse4001Fields {
    /**
     * Path of the failed property
     * @type {string}
     * @memberof InlineResponse4001Fields
     */
    path?: string;
    /**
     * Error description about validation failed field
     * @type {string}
     * @memberof InlineResponse4001Fields
     */
    message?: string;
    /**
     * Localized Key Name
     * @type {string}
     * @memberof InlineResponse4001Fields
     */
    localizationKey?: string;
}
