/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Error Bean
 * @export
 * @interface InlineResponse4001
 */
export interface InlineResponse4001 {
    /**
     * Error code
     * @type {string}
     * @memberof InlineResponse4001
     */
    code: string;
    /**
     * Error message
     * @type {string}
     * @memberof InlineResponse4001
     */
    message: string;
    /**
     * Localization Key Name
     * @type {string}
     * @memberof InlineResponse4001
     */
    localizationKey?: string;
    /**
     * Correlation Id
     * @type {string}
     * @memberof InlineResponse4001
     */
    correlationId?: string;
    /**
     * Error Detail
     * @type {string}
     * @memberof InlineResponse4001
     */
    detail?: string;
    /**
     * Error fields List
     * @type {Array<any>}
     * @memberof InlineResponse4001
     */
    fields?: Array<any>;
}
