/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse400Details } from './inline-response400-details';
/**
 * 
 * @export
 * @interface InlineResponse400Errors
 */
export interface InlineResponse400Errors {
    /**
     * The type of error.
     * @type {string}
     * @memberof InlineResponse400Errors
     */
    type?: string;
    /**
     * The detailed message related to the type stated above.
     * @type {string}
     * @memberof InlineResponse400Errors
     */
    message?: string;
    /**
     * 
     * @type {Array<InlineResponse400Details>}
     * @memberof InlineResponse400Errors
     */
    details?: Array<InlineResponse400Details>;
}
