/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {any}
     * @memberof InlineResponse200
     */
    links?: any;
    /**
     * The id of the Customer Token.
     * @type {string}
     * @memberof InlineResponse200
     */
    id?: string;
    /**
     * 
     * @type {any}
     * @memberof InlineResponse200
     */
    objectInformation?: any;
    /**
     * 
     * @type {any}
     * @memberof InlineResponse200
     */
    buyerInformation?: any;
    /**
     * 
     * @type {any}
     * @memberof InlineResponse200
     */
    clientReferenceInformation?: any;
    /**
     * Object containing the custom data that the merchant defines. 
     * @type {Array<any>}
     * @memberof InlineResponse200
     */
    merchantDefinedInformation?: Array<any>;
    /**
     * 
     * @type {any}
     * @memberof InlineResponse200
     */
    defaultPaymentInstrument?: any;
    /**
     * 
     * @type {any}
     * @memberof InlineResponse200
     */
    defaultShippingAddress?: any;
    /**
     * 
     * @type {any}
     * @memberof InlineResponse200
     */
    metadata?: any;
    /**
     * Additional resources for the Customer token. 
     * @type {any}
     * @memberof InlineResponse200
     */
    embedded?: any;
}
