/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse400Details
 */
export interface InlineResponse400Details {
    /**
     * The name of the field that caused the error.
     * @type {string}
     * @memberof InlineResponse400Details
     */
    name?: string;
    /**
     * The location of the field that caused the error.
     * @type {string}
     * @memberof InlineResponse400Details
     */
    location?: string;
}
