/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Invoicingv2invoiceSettingsInvoiceSettingsInformationHeaderStyle } from './invoicingv2invoice-settings-invoice-settings-information-header-style';
/**
 * 
 * @export
 * @interface Invoicingv2invoiceSettingsInvoiceSettingsInformation
 */
export interface Invoicingv2invoiceSettingsInvoiceSettingsInformation {
    /**
     * The image file, which must be encoded in Base64 format. Supported file formats are `png`, `jpg`, and `gif`. The image file size restriction is 1 MB.
     * @type {string}
     * @memberof Invoicingv2invoiceSettingsInvoiceSettingsInformation
     */
    merchantLogo?: string;
    /**
     * The merchant's display name shown on the invoice.
     * @type {string}
     * @memberof Invoicingv2invoiceSettingsInvoiceSettingsInformation
     */
    merchantDisplayName?: string;
    /**
     * The content of the email message that we send to your customers.
     * @type {string}
     * @memberof Invoicingv2invoiceSettingsInvoiceSettingsInformation
     */
    customEmailMessage?: string;
    /**
     * Whether you would like us to send an auto-generated reminder email to your invoice recipients. Currently, this reminder email is sent five days before the invoice is due and one day after it is past due.
     * @type {boolean}
     * @memberof Invoicingv2invoiceSettingsInvoiceSettingsInformation
     */
    enableReminders?: boolean;
    /**
     * 
     * @type {Invoicingv2invoiceSettingsInvoiceSettingsInformationHeaderStyle}
     * @memberof Invoicingv2invoiceSettingsInvoiceSettingsInformation
     */
    headerStyle?: Invoicingv2invoiceSettingsInvoiceSettingsInformationHeaderStyle;
    /**
     * The language of the email that we send to your customers. Possible values are `zh-CN`, `zh-TW`, `en-US`, `fr-FR`, `de-DE`, `ja-JP`, `pt-BR`, `ru-RU` and `es-419`.
     * @type {string}
     * @memberof Invoicingv2invoiceSettingsInvoiceSettingsInformation
     */
    deliveryLanguage?: string;
    /**
     * Currency used for the order. Use the three-character [ISO Standard Currency Codes.](http://apps.cybersource.com/library/documentation/sbc/quickref/currencies.pdf)  #### Used by **Authorization** Required field.  **Authorization Reversal** For an authorization reversal (`reversalInformation`) or a capture (`processingOptions.capture` is set to `true`), you must use the same currency that you used in your payment authorization request.  #### PIN Debit Currency for the amount you requested for the PIN debit purchase. This value is returned for partial authorizations. The issuing bank can approve a partial amount if the balance on the debit card is less than the requested transaction amount. For the possible values, see the [ISO Standard Currency Codes](https://developer.cybersource.com/library/documentation/sbc/quickref/currencies.pdf). Returned by PIN debit purchase.  For PIN debit reversal requests, you must use the same currency that was used for the PIN debit purchase or PIN debit credit that you are reversing. For the possible values, see the [ISO Standard Currency Codes](https://developer.cybersource.com/library/documentation/sbc/quickref/currencies.pdf).  Required field for PIN Debit purchase and PIN Debit credit requests. Optional field for PIN Debit reversal requests.  #### GPX This field is optional for reversing an authorization or credit.  #### DCC for First Data Your local currency. For details, see the `currency` field description in [Dynamic Currency Conversion For First Data Using the SCMP API](http://apps.cybersource.com/library/documentation/dev_guides/DCC_FirstData_SCMP/DCC_FirstData_SCMP_API.pdf).  #### Tax Calculation Required for international tax and value added tax only. Optional for U.S. and Canadian taxes. Your local currency. 
     * @type {string}
     * @memberof Invoicingv2invoiceSettingsInvoiceSettingsInformation
     */
    defaultCurrencyCode?: string;
    /**
     * For a merchant's invoice payments, enable 3D Secure payer authentication version 1, update to 3D Secure version 2, or disable 3D Secure. Possible values are:  - `enable` - `update` - `disable`  
     * @type {string}
     * @memberof Invoicingv2invoiceSettingsInvoiceSettingsInformation
     */
    payerAuthenticationInInvoicing?: string;
}
