/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InvoicingV2InvoicesCancel200ResponseOrderInformationAmountDetails } from './invoicing-v2-invoices-cancel200-response-order-information-amount-details';
import { Invoicingv2invoicesOrderInformationLineItems } from './invoicingv2invoices-order-information-line-items';
/**
 * Contains all of the order-related fields for the invoice.
 * @export
 * @interface InvoicingV2InvoicesCancel200ResponseOrderInformation
 */
export interface InvoicingV2InvoicesCancel200ResponseOrderInformation {
    /**
     * 
     * @type {InvoicingV2InvoicesCancel200ResponseOrderInformationAmountDetails}
     * @memberof InvoicingV2InvoicesCancel200ResponseOrderInformation
     */
    amountDetails?: InvoicingV2InvoicesCancel200ResponseOrderInformationAmountDetails;
    /**
     * 
     * @type {Array<Invoicingv2invoicesOrderInformationLineItems>}
     * @memberof InvoicingV2InvoicesCancel200ResponseOrderInformation
     */
    lineItems?: Array<Invoicingv2invoicesOrderInformationLineItems>;
}
