/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InvoicingV2InvoicesGet200ResponseTransactionDetails } from './invoicing-v2-invoices-get200-response-transaction-details';
/**
 * 
 * @export
 * @interface InvoicingV2InvoicesGet200ResponseInvoiceHistory
 */
export interface InvoicingV2InvoicesGet200ResponseInvoiceHistory {
    /**
     * The event triggered for the invoice.  Possible values:  - `CREATE`  - `UPDATE`  - `SEND`  - `RESEND`  - `REMINDER`  - `PAYMENT`  - `CANCEL` 
     * @type {string}
     * @memberof InvoicingV2InvoicesGet200ResponseInvoiceHistory
     */
    event?: string;
    /**
     * The date and time when the invoice event was triggered in ISO 8601 format. Format: YYYY-MM-DDThh:mm:ssZ 
     * @type {Date}
     * @memberof InvoicingV2InvoicesGet200ResponseInvoiceHistory
     */
    date?: Date;
    /**
     * 
     * @type {InvoicingV2InvoicesGet200ResponseTransactionDetails}
     * @memberof InvoicingV2InvoicesGet200ResponseInvoiceHistory
     */
    transactionDetails?: InvoicingV2InvoicesGet200ResponseTransactionDetails;
}
