/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentinstrumentsPaymentInstrumentTokenIdBody1 } from './paymentinstruments-payment-instrument-token-id-body1';
/**
 * Payment Instrument Resources. 
 * @export
 * @interface PaymentInstrumentListEmbedded
 */
export interface PaymentInstrumentListEmbedded {
    /**
     * 
     * @type {Array<PaymentinstrumentsPaymentInstrumentTokenIdBody1>}
     * @memberof PaymentInstrumentListEmbedded
     */
    paymentInstruments?: Array<PaymentinstrumentsPaymentInstrumentTokenIdBody1>;
}
