/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentInstrumentListLinksFirst } from './payment-instrument-list-links-first';
import { PaymentInstrumentListLinksLast } from './payment-instrument-list-links-last';
import { PaymentInstrumentListLinksNext } from './payment-instrument-list-links-next';
import { PaymentInstrumentListLinksPrev } from './payment-instrument-list-links-prev';
import { PaymentInstrumentListLinksSelf } from './payment-instrument-list-links-self';
/**
 * 
 * @export
 * @interface PaymentInstrumentListLinks
 */
export interface PaymentInstrumentListLinks {
    /**
     * 
     * @type {PaymentInstrumentListLinksSelf}
     * @memberof PaymentInstrumentListLinks
     */
    self?: PaymentInstrumentListLinksSelf;
    /**
     * 
     * @type {PaymentInstrumentListLinksFirst}
     * @memberof PaymentInstrumentListLinks
     */
    first?: PaymentInstrumentListLinksFirst;
    /**
     * 
     * @type {PaymentInstrumentListLinksPrev}
     * @memberof PaymentInstrumentListLinks
     */
    prev?: PaymentInstrumentListLinksPrev;
    /**
     * 
     * @type {PaymentInstrumentListLinksNext}
     * @memberof PaymentInstrumentListLinks
     */
    next?: PaymentInstrumentListLinksNext;
    /**
     * 
     * @type {PaymentInstrumentListLinksLast}
     * @memberof PaymentInstrumentListLinks
     */
    last?: PaymentInstrumentListLinksLast;
}
