/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaymentInstrumentListEmbedded } from './payment-instrument-list-embedded';
import { PaymentInstrumentListLinks } from './payment-instrument-list-links';
/**
 * 
 * @export
 * @interface PaymentInstrumentList
 */
export interface PaymentInstrumentList {
    /**
     * 
     * @type {PaymentInstrumentListLinks}
     * @memberof PaymentInstrumentList
     */
    links?: PaymentInstrumentListLinks;
    /**
     * The offset parameter supplied in the request.
     * @type {number}
     * @memberof PaymentInstrumentList
     */
    offset?: number;
    /**
     * The limit parameter supplied in the request.
     * @type {number}
     * @memberof PaymentInstrumentList
     */
    limit?: number;
    /**
     * The number of Payment Instruments returned in the array.
     * @type {number}
     * @memberof PaymentInstrumentList
     */
    count?: number;
    /**
     * The total number of Payment Instruments associated with the Customer or Instrument Identifier.
     * @type {number}
     * @memberof PaymentInstrumentList
     */
    total?: number;
    /**
     * 
     * @type {PaymentInstrumentListEmbedded}
     * @memberof PaymentInstrumentList
     */
    embedded?: PaymentInstrumentListEmbedded;
}
