/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PtsV2IncrementalAuthorizationPatch201ResponseProcessorInformationMerchantAdvice } from './pts-v2-incremental-authorization-patch201-response-processor-information-merchant-advice';
import { PtsV2PaymentsPost201ResponseProcessorInformationCardVerification } from './pts-v2-payments-post201-response-processor-information-card-verification';
import { PtsV2PaymentsPost201ResponseProcessorInformationConsumerAuthenticationResponse } from './pts-v2-payments-post201-response-processor-information-consumer-authentication-response';
import { PtsV2PaymentsPost201ResponseProcessorInformationCustomer } from './pts-v2-payments-post201-response-processor-information-customer';
import { PtsV2PaymentsPost201ResponseProcessorInformationElectronicVerificationResults } from './pts-v2-payments-post201-response-processor-information-electronic-verification-results';
import { PtsV2PaymentsPost201ResponseProcessorInformationRouting } from './pts-v2-payments-post201-response-processor-information-routing';
import { TssV2TransactionsGet200ResponseProcessorInformationAchVerification } from './tss-v2-transactions-get200-response-processor-information-ach-verification';
import { TssV2TransactionsGet200ResponseProcessorInformationAvs } from './tss-v2-transactions-get200-response-processor-information-avs';
/**
 * 
 * @export
 * @interface PtsV2PaymentsPost201ResponseProcessorInformation
 */
export interface PtsV2PaymentsPost201ResponseProcessorInformation {
    /**
     * Flag that specifies the purpose of the authorization.  Possible values:  - `0`: Preauthorization  - `1`: Final authorization 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    authIndicator?: string;
    /**
     * Authorization code. Returned only when the processor returns this value.  The length of this value depends on your processor.  Returned by authorization service.  #### PIN debit Authorization code that is returned by the processor.  Returned by PIN debit credit.  #### Elavon Encrypted Account Number Program The returned value is OFFLINE.  #### TSYS Acquiring Solutions The returned value for a successful zero amount authorization is 000000. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    approvalCode?: string;
    /**
     * The Scheme reference data is a variable length data element up to a maximum of 56 characters. It may be sent by the acquirer in the authorisation response message, and by the terminal (unchanged) in subsequent authorisation request messages associated with the same transaction. This field is used by Streamline and HSBC UK only, at present. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    cardReferenceData?: string;
    /**
     * Network transaction identifier (TID). You can use this value to identify a specific transaction when you are discussing the transaction with your processor. Not all processors provide this value.  Returned by the authorization service.  #### PIN debit Transaction identifier generated by the processor.  Returned by PIN debit credit.  #### GPX Processor transaction ID.  #### Cielo For Cielo, this value is the non-sequential unit (NSU) and is supported for all transactions. The value is generated by Cielo or the issuing bank.  #### Comercio Latino For Comercio Latino, this value is the proof of sale or non-sequential unit (NSU) number generated by the acquirers Cielo and Rede, or the issuing bank.  #### CyberSource through VisaNet and GPN For details about this value for CyberSource through VisaNet and GPN, see \"Network Transaction Identifiers\" in [Credit Card Services Using the SCMP API.](https://apps.cybersource.com/library/documentation/dev_guides/CC_Svcs_SCMP_API/html/)  #### Moneris This value identifies the transaction on a host system. It contains the following information: - Terminal used to process the transaction - Shift during which the transaction took place - Batch number - Transaction number within the batch You must store this value. If you give the customer a receipt, display this value on the receipt.  **Example** For the value 66012345001069003: - Terminal ID = 66012345 - Shift number = 001 - Batch number = 069 - Transaction number = 003 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    transactionId?: string;
    /**
     * Same value as `processorInformation.transactionId`
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    networkTransactionId?: string;
    /**
     * For most processors, this is the error message sent directly from the bank. Returned only when the processor returns this value.  **Important** Do not use this field to evaluate the result of the authorization.  #### PIN debit Response value that is returned by the processor or bank. **Important** Do not use this field to evaluate the results of the transaction request.  Returned by PIN debit credit, PIN debit purchase, and PIN debit reversal.  #### AIBMS If this value is `08`, you can accept the transaction if the customer provides you with identification.  #### Atos This value is the response code sent from Atos and it might also include the response code from the bank. Format: `aa,bb` with the two values separated by a comma and where: - `aa` is the two-digit error message from Atos. - `bb` is the optional two-digit error message from the bank.  #### Comercio Latino This value is the status code and the error or response code received from the processor separated by a colon. Format: [status code]:E[error code] or [status code]:R[response code] Example `2:R06`  #### JCN Gateway Processor-defined detail error code. The associated response category code is in the `processorInformation.responseCategoryCode` field. String (3) 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    responseCode?: string;
    /**
     * Used by Visa only and contains the response source/reason code that identifies the source of the response decision. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    responseCodeSource?: string;
    /**
     * This field might contain information about a decline. This field is supported only for **CyberSource through VisaNet**. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    responseDetails?: string;
    /**
     * Processor-defined response category code. The associated detail error code is in the `processorInformation.responseCode` or `issuerInformation.responseCode` field of the service you requested.  This field is supported only for:   - Japanese issuers  - Domestic transactions in Japan  - Comercio Latino—processor transaction ID required for troubleshooting  #### Maximum length for processors   - Comercio Latino: 36  - All other processors: 3 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    responseCategoryCode?: string;
    /**
     * Name of the Japanese acquirer that processed the transaction. Returned only for JCN Gateway. Please contact the CyberSource Japan Support Group for more information. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    forwardedAcquirerCode?: string;
    /**
     * 
     * @type {TssV2TransactionsGet200ResponseProcessorInformationAvs}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    avs?: TssV2TransactionsGet200ResponseProcessorInformationAvs;
    /**
     * 
     * @type {PtsV2PaymentsPost201ResponseProcessorInformationCardVerification}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    cardVerification?: PtsV2PaymentsPost201ResponseProcessorInformationCardVerification;
    /**
     * 
     * @type {PtsV2IncrementalAuthorizationPatch201ResponseProcessorInformationMerchantAdvice}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    merchantAdvice?: PtsV2IncrementalAuthorizationPatch201ResponseProcessorInformationMerchantAdvice;
    /**
     * 
     * @type {PtsV2PaymentsPost201ResponseProcessorInformationElectronicVerificationResults}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    electronicVerificationResults?: PtsV2PaymentsPost201ResponseProcessorInformationElectronicVerificationResults;
    /**
     * 
     * @type {TssV2TransactionsGet200ResponseProcessorInformationAchVerification}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    achVerification?: TssV2TransactionsGet200ResponseProcessorInformationAchVerification;
    /**
     * 
     * @type {PtsV2PaymentsPost201ResponseProcessorInformationCustomer}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    customer?: PtsV2PaymentsPost201ResponseProcessorInformationCustomer;
    /**
     * 
     * @type {PtsV2PaymentsPost201ResponseProcessorInformationConsumerAuthenticationResponse}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    consumerAuthenticationResponse?: PtsV2PaymentsPost201ResponseProcessorInformationConsumerAuthenticationResponse;
    /**
     * This field is returned only for **American Express Direct** and **CyberSource through VisaNet**. Returned by authorization and incremental authorization services.  #### American Express Direct  System trace audit number (STAN). This value identifies the transaction and is useful when investigating a chargeback dispute.  #### CyberSource through VisaNet  System trace number that must be printed on the customer’s receipt. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    systemTraceAuditNumber?: string;
    /**
     * Visa-generated reference number that identifies a card-present transaction for which you provided one of the following:   - Visa primary account number (PAN)  - Visa-generated token for a PAN  This reference number serves as a link to the cardholder account and to all transactions for that account. This reply field is returned only for CyberSource through VisaNet.  **Note** On CyberSource through VisaNet, the value for this field corresponds to the following data in the TC 33 capture file: - Record: CP01 TCR8 - Position: 79-110 - Field: Payment Account Reference  The TC 33 Capture file contains information about the purchases and refunds that a merchant submits to CyberSource. CyberSource through VisaNet creates the TC 33 Capture file at the end of the day and sends it to the merchant’s acquirer, who uses this information to facilitate end-of-day clearing processing with payment networks. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    paymentAccountReferenceNumber?: string;
    /**
     * Transaction integrity classification provided by Mastercard. This value specifies Mastercard’s evaluation of the transaction’s safety and security. This field is returned only for **CyberSource through VisaNet**.  For card-present transactions, possible values:   - `A1`: EMV or token in a secure, trusted environment  - `B1`: EMV or chip equivalent  - `C1`: Magnetic stripe  - `E1`: Key entered  - `U0`: Unclassified  For card-not-present transactions, possible values:   - `A2`: Digital transactions  - `B2`: Authenticated checkout  - `C2`: Transaction validation  - `D2`: Enhanced data  - `E2`: Generic messaging  - `U0`: Unclassified  For information about these values, contact Mastercard or your acquirer.  #### CyberSource through VisaNet  The value for this field corresponds to the following data in the TC 33 capture file,<sup>1</sup>: - Record: CP01 TCR6 - Position: 136-137 - Field: Mastercard Transaction Integrity Classification  <sup>1</sup> The TC 33 Capture file contains information about the purchases and refunds that a merchant submits to CyberSource. CyberSource through VisaNet creates the TC 33 Capture file at the end of the day and sends it to the merchant’s acquirer, who uses this information to facilitate end-of-day clearing processing with payment networks. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    transactionIntegrityCode?: string;
    /**
     * Referral response number for a verbal authorization with FDMS Nashville when using an American Express card. Give this number to American Express when you call them for the verbal authorization. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    amexVerbalAuthReferenceNumber?: string;
    /**
     * Mastercard service that was used for the transaction. Mastercard provides this value to CyberSource.  Possible value:  - 53: Mastercard card-on-file token service  #### CyberSource through VisaNet The value for this field corresponds to the following data in the TC 33 capture file: - Record: CP01 TCR6 - Position: 133-134 - Field: Mastercard Merchant on-behalf service. **Note** This field is returned only for CyberSource through VisaNet. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    masterCardServiceCode?: string;
    /**
     * Result of the Mastercard card-on-file token service. Mastercard provides this value to CyberSource.  Possible values:   - `C`: Service completed successfully.  - `F`: One of the following:    - Incorrect Mastercard POS entry mode. The Mastercard POS entry mode should be 81 for an authorization or      authorization reversal.    - Incorrect Mastercard POS entry mode. The Mastercard POS entry mode should be 01 for a tokenized request.    - Token requestor ID is missing or formatted incorrectly.  - `I`: One of the following:    - Invalid token requestor ID.    - Suspended or deactivated token.    - Invalid token (not in mapping table).  - `T`: Invalid combination of token requestor ID and token.  - `U`: Expired token.  - `W`: Primary account number (PAN) listed in electronic warning bulletin.  **Note** This field is returned only for **CyberSource through VisaNet**. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    masterCardServiceReplyCode?: string;
    /**
     * Type of authentication for which the transaction qualifies as determined by the Mastercard authentication service, which confirms the identity of the cardholder. Mastercard provides this value to CyberSource.  Possible values:   - `1`: Transaction qualifies for Mastercard authentication type 1.  - `2`: Transaction qualifies for Mastercard authentication type 2.  #### CyberSource through VisaNet The value for this field corresponds to the following data in the TC 33 capture file: - Record: CP01 TCR6 - Position: 132 - Field: Mastercard Member Defined service. **Note** This field is returned only for CyberSource through VisaNet. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    masterCardAuthenticationType?: string;
    /**
     * Name of the Processor. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    name?: string;
    /**
     * 
     * @type {PtsV2PaymentsPost201ResponseProcessorInformationRouting}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    routing?: PtsV2PaymentsPost201ResponseProcessorInformationRouting;
    /**
     * Identifier that was assigned to you by your acquirer. This value must be printed on the receipt.  #### Returned by Authorizations and Credits.  This reply field is only supported by merchants who have installed client software on their POS terminals and use these processors: - American Express Direct - Credit Mutuel-CIC - FDC Nashville Global - OmniPay Direct - SIX 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    merchantNumber?: string;
    /**
     * #### Ingenico ePayments Unique number that CyberSource generates to identify the transaction. You can use this value to identify transactions in the Ingenico ePayments Collections Report, which provides settlement information. Contact customer support for information about the report.  ### CyberSource through VisaNet Retrieval request number. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    retrievalReferenceNumber?: string;
    /**
     * Direct the customer to this URL to complete the payment.
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    paymentUrl?: string;
    /**
     * The redirect URL for forwarding the consumer to complete page.  This redirect needed by PSP to track browser information of consumer. PSP then redirect consumer to merchant success URL. 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponseProcessorInformation
     */
    completeUrl?: string;
}
