/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PtsV2RefundsVoidsPost201ResponseLinksSelf } from './pts-v2-refunds-voids-post201-response-links-self';
/**
 * 
 * @export
 * @interface PtsV2PaymentsCapturesPost201ResponseLinks
 */
export interface PtsV2PaymentsCapturesPost201ResponseLinks {
    /**
     * 
     * @type {PtsV2RefundsVoidsPost201ResponseLinksSelf}
     * @memberof PtsV2PaymentsCapturesPost201ResponseLinks
     */
    self?: PtsV2RefundsVoidsPost201ResponseLinksSelf;
    /**
     * 
     * @type {PtsV2RefundsVoidsPost201ResponseLinksSelf}
     * @memberof PtsV2PaymentsCapturesPost201ResponseLinks
     */
    _void?: PtsV2RefundsVoidsPost201ResponseLinksSelf;
    /**
     * 
     * @type {PtsV2RefundsVoidsPost201ResponseLinksSelf}
     * @memberof PtsV2PaymentsCapturesPost201ResponseLinks
     */
    refund?: PtsV2RefundsVoidsPost201ResponseLinksSelf;
}
