/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PtsV2IncrementalAuthorizationPatch201ResponseClientReferenceInformation } from './pts-v2-incremental-authorization-patch201-response-client-reference-information';
import { PtsV2IncrementalAuthorizationPatch201ResponseErrorInformation } from './pts-v2-incremental-authorization-patch201-response-error-information';
import { PtsV2IncrementalAuthorizationPatch201ResponseOrderInformation } from './pts-v2-incremental-authorization-patch201-response-order-information';
import { PtsV2IncrementalAuthorizationPatch201ResponsePaymentInformation } from './pts-v2-incremental-authorization-patch201-response-payment-information';
import { PtsV2IncrementalAuthorizationPatch201ResponseProcessorInformation } from './pts-v2-incremental-authorization-patch201-response-processor-information';
import { PtsV2RefundsVoidsPost201ResponseLinks } from './pts-v2-refunds-voids-post201-response-links';
/**
 * 
 * @export
 * @interface PtsV2IncrementalAuthorizationPatch201Response
 */
export interface PtsV2IncrementalAuthorizationPatch201Response {
    /**
     * 
     * @type {PtsV2RefundsVoidsPost201ResponseLinks}
     * @memberof PtsV2IncrementalAuthorizationPatch201Response
     */
    links?: PtsV2RefundsVoidsPost201ResponseLinks;
    /**
     * An unique identification number generated by Cybersource to identify the submitted request. Returned by all services. It is also appended to the endpoint of the resource. On incremental authorizations, this value with be the same as the identification number returned in the original authorization response. 
     * @type {string}
     * @memberof PtsV2IncrementalAuthorizationPatch201Response
     */
    id?: string;
    /**
     * Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ` **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.). The `T` separates the date and the time. The `Z` indicates UTC.  Returned by Cybersource for all services. 
     * @type {string}
     * @memberof PtsV2IncrementalAuthorizationPatch201Response
     */
    submitTimeUtc?: string;
    /**
     * The status of the submitted transaction.  Possible values:  - AUTHORIZED  - AUTHORIZED_PENDING_REVIEW  - DECLINED 
     * @type {string}
     * @memberof PtsV2IncrementalAuthorizationPatch201Response
     */
    status?: string;
    /**
     * Reference number for the transaction. Depending on how your Cybersource account is configured, this value could either be provided in the API request or generated by CyberSource. The actual value used in the request to the processor is provided back to you by Cybersource in the response. 
     * @type {string}
     * @memberof PtsV2IncrementalAuthorizationPatch201Response
     */
    reconciliationId?: string;
    /**
     * 
     * @type {PtsV2IncrementalAuthorizationPatch201ResponseErrorInformation}
     * @memberof PtsV2IncrementalAuthorizationPatch201Response
     */
    errorInformation?: PtsV2IncrementalAuthorizationPatch201ResponseErrorInformation;
    /**
     * 
     * @type {PtsV2IncrementalAuthorizationPatch201ResponseClientReferenceInformation}
     * @memberof PtsV2IncrementalAuthorizationPatch201Response
     */
    clientReferenceInformation?: PtsV2IncrementalAuthorizationPatch201ResponseClientReferenceInformation;
    /**
     * 
     * @type {PtsV2IncrementalAuthorizationPatch201ResponseProcessorInformation}
     * @memberof PtsV2IncrementalAuthorizationPatch201Response
     */
    processorInformation?: PtsV2IncrementalAuthorizationPatch201ResponseProcessorInformation;
    /**
     * 
     * @type {PtsV2IncrementalAuthorizationPatch201ResponsePaymentInformation}
     * @memberof PtsV2IncrementalAuthorizationPatch201Response
     */
    paymentInformation?: PtsV2IncrementalAuthorizationPatch201ResponsePaymentInformation;
    /**
     * 
     * @type {PtsV2IncrementalAuthorizationPatch201ResponseOrderInformation}
     * @memberof PtsV2IncrementalAuthorizationPatch201Response
     */
    orderInformation?: PtsV2IncrementalAuthorizationPatch201ResponseOrderInformation;
}
