/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PtsV2PayoutsPost201ResponseOrderInformationAmountDetails } from './pts-v2-payouts-post201-response-order-information-amount-details';
/**
 * 
 * @export
 * @interface PtsV2PayoutsPost201ResponseOrderInformation
 */
export interface PtsV2PayoutsPost201ResponseOrderInformation {
    /**
     * 
     * @type {PtsV2PayoutsPost201ResponseOrderInformationAmountDetails}
     * @memberof PtsV2PayoutsPost201ResponseOrderInformation
     */
    amountDetails?: PtsV2PayoutsPost201ResponseOrderInformationAmountDetails;
}
