/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PtsV2RefundsVoidsPost201ResponseLinksSelf
 */
export interface PtsV2RefundsVoidsPost201ResponseLinksSelf {
    /**
     * This is the endpoint of the resource that was created by the successful request.
     * @type {string}
     * @memberof PtsV2RefundsVoidsPost201ResponseLinksSelf
     */
    href?: string;
    /**
     * `method` refers to the HTTP method that you can send to the `self` endpoint to retrieve details of the resource.
     * @type {string}
     * @memberof PtsV2RefundsVoidsPost201ResponseLinksSelf
     */
    method?: string;
}
