/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PtsV2PaymentsPost201ResponsePaymentAccountInformationCard } from './pts-v2-payments-post201-response-payment-account-information-card';
import { PtsV2PaymentsPost201ResponsePaymentInformationAccountFeatures } from './pts-v2-payments-post201-response-payment-information-account-features';
import { PtsV2PaymentsPost201ResponsePaymentInformationBank } from './pts-v2-payments-post201-response-payment-information-bank';
import { PtsV2PaymentsPost201ResponsePaymentInformationInstrumentIdentifier } from './pts-v2-payments-post201-response-payment-information-instrument-identifier';
import { PtsV2PaymentsPost201ResponsePaymentInformationTokenizedCard } from './pts-v2-payments-post201-response-payment-information-tokenized-card';
import { Ptsv2paymentsPaymentInformationCustomer } from './ptsv2payments-payment-information-customer';
import { Ptsv2paymentsPaymentInformationPaymentInstrument } from './ptsv2payments-payment-information-payment-instrument';
import { Ptsv2paymentsPaymentInformationShippingAddress } from './ptsv2payments-payment-information-shipping-address';
/**
 * 
 * @export
 * @interface PtsV2PaymentsPost201ResponsePaymentInformation
 */
export interface PtsV2PaymentsPost201ResponsePaymentInformation {
    /**
     * 
     * @type {PtsV2PaymentsPost201ResponsePaymentAccountInformationCard}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    card?: PtsV2PaymentsPost201ResponsePaymentAccountInformationCard;
    /**
     * 
     * @type {PtsV2PaymentsPost201ResponsePaymentInformationTokenizedCard}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    tokenizedCard?: PtsV2PaymentsPost201ResponsePaymentInformationTokenizedCard;
    /**
     * 
     * @type {PtsV2PaymentsPost201ResponsePaymentInformationAccountFeatures}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    accountFeatures?: PtsV2PaymentsPost201ResponsePaymentInformationAccountFeatures;
    /**
     * 
     * @type {PtsV2PaymentsPost201ResponsePaymentInformationBank}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    bank?: PtsV2PaymentsPost201ResponsePaymentInformationBank;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationCustomer}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    customer?: Ptsv2paymentsPaymentInformationCustomer;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationPaymentInstrument}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    paymentInstrument?: Ptsv2paymentsPaymentInformationPaymentInstrument;
    /**
     * 
     * @type {PtsV2PaymentsPost201ResponsePaymentInformationInstrumentIdentifier}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    instrumentIdentifier?: PtsV2PaymentsPost201ResponsePaymentInformationInstrumentIdentifier;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationShippingAddress}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    shippingAddress?: Ptsv2paymentsPaymentInformationShippingAddress;
    /**
     * Subtype of card account. This field can contain one of the following values: - Maestro International - Maestro UK Domestic - MasterCard Credit - MasterCard Debit - Visa Credit - Visa Debit - Visa Electron  **Note** Additional values may be present.  For all possible values, see the `score_card_scheme` field description in the _Decision Manager Using the SCMP API Developer Guide_ on the [CyberSource Business Center.](https://ebc2.cybersource.com/ebc2/) Click **Decision Manager** > **Documentation** > **Guides** > _Decision Manager Using the SCMP API Developer Guide_ (PDF link). 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    scheme?: string;
    /**
     * Credit card BIN (the first six digits of the credit card).Derived either from the `cc_bin` request field or from the first six characters of the `customer_cc_num` field.  For all possible values, see the `score_cc_bin` field description in the _Decision Manager Using the SCMP API Developer Guide_ on the [CyberSource Business Center.](https://ebc2.cybersource.com/ebc2/) Click **Decision Manager** > **Documentation** > **Guides** > _Decision Manager Using the SCMP API Developer Guide_ (PDF link). 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    bin?: string;
    /**
     * Type of payment card account. This field can refer to a credit card, debit card, or prepaid card account type.  For all possible values, see the `score_card_account_type` field description in the _Decision Manager Using the SCMP API Developer Guide_ on the [CyberSource Business Center.](https://ebc2.cybersource.com/ebc2/) Click **Decision Manager** > **Documentation** > **Guides** > _Decision Manager Using the SCMP API Developer Guide_ (PDF link). 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    accountType?: string;
    /**
     * Name of the bank or entity that issued the card account.  For all possible values, see the `score_card_issuer` field description in the _Decision Manager Using the SCMP API Developer Guide_ on the [CyberSource Business Center.](https://ebc2.cybersource.com/ebc2/) Click **Decision Manager** > **Documentation** > **Guides** > _Decision Manager Using the SCMP API Developer Guide_ (PDF link). 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    issuer?: string;
    /**
     * Country (two-digit country code) associated with the BIN of the customer’s card used for the payment. Returned if the information is available. Use this field for additional information when reviewing orders. This information is also displayed in the details page of the CyberSource Business Center.  For all possible values, see the `bin_country` field description in the _Decision Manager Using the SCMP API Developer Guide_ on the [CyberSource Business Center.](https://ebc2.cybersource.com/ebc2/) Click **Decision Manager** > **Documentation** > **Guides** > _Decision Manager Using the SCMP API Developer Guide_ (PDF link). 
     * @type {string}
     * @memberof PtsV2PaymentsPost201ResponsePaymentInformation
     */
    binCountry?: string;
}
