/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PtsV2CreditsPost201ResponseCreditAmountDetails } from './pts-v2-credits-post201-response-credit-amount-details';
import { PtsV2CreditsPost201ResponsePaymentInformation } from './pts-v2-credits-post201-response-payment-information';
import { PtsV2CreditsPost201ResponseProcessingInformation } from './pts-v2-credits-post201-response-processing-information';
import { PtsV2PaymentsCapturesPost201ResponsePointOfSaleInformation } from './pts-v2-payments-captures-post201-response-point-of-sale-information';
import { PtsV2PaymentsRefundPost201ResponseLinks } from './pts-v2-payments-refund-post201-response-links';
import { PtsV2PaymentsRefundPost201ResponseOrderInformation } from './pts-v2-payments-refund-post201-response-order-information';
import { PtsV2PaymentsRefundPost201ResponseProcessorInformation } from './pts-v2-payments-refund-post201-response-processor-information';
import { PtsV2RefundsVoidsPost201ResponseClientReferenceInformation } from './pts-v2-refunds-voids-post201-response-client-reference-information';
/**
 * 
 * @export
 * @interface PtsV2CreditsPost201Response
 */
export interface PtsV2CreditsPost201Response {
    /**
     * 
     * @type {PtsV2PaymentsRefundPost201ResponseLinks}
     * @memberof PtsV2CreditsPost201Response
     */
    links?: PtsV2PaymentsRefundPost201ResponseLinks;
    /**
     * An unique identification number generated by Cybersource to identify the submitted request. Returned by all services. It is also appended to the endpoint of the resource. On incremental authorizations, this value with be the same as the identification number returned in the original authorization response. 
     * @type {string}
     * @memberof PtsV2CreditsPost201Response
     */
    id?: string;
    /**
     * Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ` **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.). The `T` separates the date and the time. The `Z` indicates UTC.  Returned by Cybersource for all services. 
     * @type {string}
     * @memberof PtsV2CreditsPost201Response
     */
    submitTimeUtc?: string;
    /**
     * The status of the submitted transaction.  Possible values:  - PENDING  - COMPLETED (as in the case of PIN Debit Full Financial Credit) 
     * @type {string}
     * @memberof PtsV2CreditsPost201Response
     */
    status?: string;
    /**
     * Reference number for the transaction. Depending on how your Cybersource account is configured, this value could either be provided in the API request or generated by CyberSource. The actual value used in the request to the processor is provided back to you by Cybersource in the response. 
     * @type {string}
     * @memberof PtsV2CreditsPost201Response
     */
    reconciliationId?: string;
    /**
     * 
     * @type {PtsV2RefundsVoidsPost201ResponseClientReferenceInformation}
     * @memberof PtsV2CreditsPost201Response
     */
    clientReferenceInformation?: PtsV2RefundsVoidsPost201ResponseClientReferenceInformation;
    /**
     * 
     * @type {PtsV2CreditsPost201ResponseCreditAmountDetails}
     * @memberof PtsV2CreditsPost201Response
     */
    creditAmountDetails?: PtsV2CreditsPost201ResponseCreditAmountDetails;
    /**
     * 
     * @type {PtsV2CreditsPost201ResponseProcessingInformation}
     * @memberof PtsV2CreditsPost201Response
     */
    processingInformation?: PtsV2CreditsPost201ResponseProcessingInformation;
    /**
     * 
     * @type {PtsV2PaymentsRefundPost201ResponseProcessorInformation}
     * @memberof PtsV2CreditsPost201Response
     */
    processorInformation?: PtsV2PaymentsRefundPost201ResponseProcessorInformation;
    /**
     * 
     * @type {PtsV2CreditsPost201ResponsePaymentInformation}
     * @memberof PtsV2CreditsPost201Response
     */
    paymentInformation?: PtsV2CreditsPost201ResponsePaymentInformation;
    /**
     * 
     * @type {PtsV2PaymentsRefundPost201ResponseOrderInformation}
     * @memberof PtsV2CreditsPost201Response
     */
    orderInformation?: PtsV2PaymentsRefundPost201ResponseOrderInformation;
    /**
     * 
     * @type {PtsV2PaymentsCapturesPost201ResponsePointOfSaleInformation}
     * @memberof PtsV2CreditsPost201Response
     */
    pointOfSaleInformation?: PtsV2PaymentsCapturesPost201ResponsePointOfSaleInformation;
}
