/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ptsv2paymentsPaymentInformationCustomer } from './ptsv2payments-payment-information-customer';
import { Ptsv2paymentsPaymentInformationEWallet } from './ptsv2payments-payment-information-ewallet';
import { Ptsv2paymentsPaymentInformationFluidData } from './ptsv2payments-payment-information-fluid-data';
import { Ptsv2paymentsPaymentInformationInstrumentIdentifier } from './ptsv2payments-payment-information-instrument-identifier';
import { Ptsv2paymentsPaymentInformationLegacyToken } from './ptsv2payments-payment-information-legacy-token';
import { Ptsv2paymentsPaymentInformationPaymentInstrument } from './ptsv2payments-payment-information-payment-instrument';
import { Ptsv2paymentsPaymentInformationPaymentType } from './ptsv2payments-payment-information-payment-type';
import { Ptsv2paymentsPaymentInformationShippingAddress } from './ptsv2payments-payment-information-shipping-address';
import { Ptsv2paymentsPaymentInformationTokenizedCard } from './ptsv2payments-payment-information-tokenized-card';
import { Ptsv2paymentsidrefundsPaymentInformationBank } from './ptsv2paymentsidrefunds-payment-information-bank';
import { Ptsv2paymentsidrefundsPaymentInformationCard } from './ptsv2paymentsidrefunds-payment-information-card';
/**
 * 
 * @export
 * @interface Ptsv2paymentsidrefundsPaymentInformation
 */
export interface Ptsv2paymentsidrefundsPaymentInformation {
    /**
     * 
     * @type {Ptsv2paymentsidrefundsPaymentInformationCard}
     * @memberof Ptsv2paymentsidrefundsPaymentInformation
     */
    card?: Ptsv2paymentsidrefundsPaymentInformationCard;
    /**
     * 
     * @type {Ptsv2paymentsidrefundsPaymentInformationBank}
     * @memberof Ptsv2paymentsidrefundsPaymentInformation
     */
    bank?: Ptsv2paymentsidrefundsPaymentInformationBank;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationTokenizedCard}
     * @memberof Ptsv2paymentsidrefundsPaymentInformation
     */
    tokenizedCard?: Ptsv2paymentsPaymentInformationTokenizedCard;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationFluidData}
     * @memberof Ptsv2paymentsidrefundsPaymentInformation
     */
    fluidData?: Ptsv2paymentsPaymentInformationFluidData;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationCustomer}
     * @memberof Ptsv2paymentsidrefundsPaymentInformation
     */
    customer?: Ptsv2paymentsPaymentInformationCustomer;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationPaymentInstrument}
     * @memberof Ptsv2paymentsidrefundsPaymentInformation
     */
    paymentInstrument?: Ptsv2paymentsPaymentInformationPaymentInstrument;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationInstrumentIdentifier}
     * @memberof Ptsv2paymentsidrefundsPaymentInformation
     */
    instrumentIdentifier?: Ptsv2paymentsPaymentInformationInstrumentIdentifier;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationShippingAddress}
     * @memberof Ptsv2paymentsidrefundsPaymentInformation
     */
    shippingAddress?: Ptsv2paymentsPaymentInformationShippingAddress;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationLegacyToken}
     * @memberof Ptsv2paymentsidrefundsPaymentInformation
     */
    legacyToken?: Ptsv2paymentsPaymentInformationLegacyToken;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationPaymentType}
     * @memberof Ptsv2paymentsidrefundsPaymentInformation
     */
    paymentType?: Ptsv2paymentsPaymentInformationPaymentType;
    /**
     * 
     * @type {Ptsv2paymentsPaymentInformationEWallet}
     * @memberof Ptsv2paymentsidrefundsPaymentInformation
     */
    eWallet?: Ptsv2paymentsPaymentInformationEWallet;
}
