/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ptsv2paymentsidcapturesPointOfSaleInformationEmv } from './ptsv2paymentsidcaptures-point-of-sale-information-emv';
/**
 * 
 * @export
 * @interface Ptsv2paymentsidrefundsPointOfSaleInformation
 */
export interface Ptsv2paymentsidrefundsPointOfSaleInformation {
    /**
     * 
     * @type {Ptsv2paymentsidcapturesPointOfSaleInformationEmv}
     * @memberof Ptsv2paymentsidrefundsPointOfSaleInformation
     */
    emv?: Ptsv2paymentsidcapturesPointOfSaleInformationEmv;
}
