/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ptsv2payoutsProcessingInformationFundingOptions } from './ptsv2payouts-processing-information-funding-options';
import { Ptsv2payoutsProcessingInformationPayoutsOptions } from './ptsv2payouts-processing-information-payouts-options';
/**
 * 
 * @export
 * @interface Ptsv2payoutsProcessingInformation
 */
export interface Ptsv2payoutsProcessingInformation {
    /**
     * Payouts transaction type.  Applicable Processors: FDC Compass, Paymentech, CtV  Possible values:  **Credit Card Bill Payment**   - **CP**: credit card bill payment  **Funds Disbursement**   - **FD**: funds disbursement  - **GD**: government disbursement  - **MD**: merchant disbursement  **Money Transfer**   - **AA**: account to account. Sender and receiver are same person.  - **PP**: person to person. Sender and receiver are different.  **Prepaid Load**   - **TU**: top up 
     * @type {string}
     * @memberof Ptsv2payoutsProcessingInformation
     */
    businessApplicationId?: string;
    /**
     * This field is optionally used by Push Payments Gateway participants (merchants and acquirers) to get the attributes for specified networks only. The networks specified in this field must be a subset of the information provided during program enrollment. Refer to Sharing Group Code/Network Routing Order. Note: Supported only in US for domestic transactions involving Push Payments Gateway Service.  VisaNet checks to determine if there are issuer routing preferences for any of the networks specified by the network routing order. If an issuer preference exists for one of the specified debit networks, VisaNet makes a routing selection based on the issuer’s preference.  If an issuer preference exists for more than one of the specified debit networks, or if no issuer preference exists, VisaNet makes a selection based on the acquirer’s routing priorities.   For details, see the `network_order` field description in [BIN Lookup Service Using the SCMP API.](http://apps.cybersource.com/library/documentation/BIN_Lookup/BIN_Lookup_SCMP_API/html/) 
     * @type {string}
     * @memberof Ptsv2payoutsProcessingInformation
     */
    networkRoutingOrder?: string;
    /**
     * Type of transaction.  Value for an OCT transaction: - `internet`  For details, see the `e_commerce_indicator` field description in [Payouts Using the SCMP API.](http://apps.cybersource.com/library/documentation/dev_guides/payouts_SCMP/html/) 
     * @type {string}
     * @memberof Ptsv2payoutsProcessingInformation
     */
    commerceIndicator?: string;
    /**
     * Please check with Cybersource customer support to see if your merchant account is configured correctly so you can include this field in your request. * For Payouts: max length for FDCCompass is String (22). 
     * @type {string}
     * @memberof Ptsv2payoutsProcessingInformation
     */
    reconciliationId?: string;
    /**
     * 
     * @type {Ptsv2payoutsProcessingInformationPayoutsOptions}
     * @memberof Ptsv2payoutsProcessingInformation
     */
    payoutsOptions?: Ptsv2payoutsProcessingInformationPayoutsOptions;
    /**
     * Transaction reason code. 
     * @type {string}
     * @memberof Ptsv2payoutsProcessingInformation
     */
    transactionReason?: string;
    /**
     * This will send purpose of funds code for original credit transactions (OCTs). 
     * @type {string}
     * @memberof Ptsv2payoutsProcessingInformation
     */
    purposeOfPayment?: string;
    /**
     * 
     * @type {Ptsv2payoutsProcessingInformationFundingOptions}
     * @memberof Ptsv2payoutsProcessingInformation
     */
    fundingOptions?: Ptsv2payoutsProcessingInformationFundingOptions;
}
