/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ptsv2paymentsTravelInformationAgency } from './ptsv2payments-travel-information-agency';
import { Ptsv2paymentsTravelInformationAutoRental } from './ptsv2payments-travel-information-auto-rental';
import { Ptsv2paymentsTravelInformationLodging } from './ptsv2payments-travel-information-lodging';
import { Ptsv2paymentsTravelInformationTransit } from './ptsv2payments-travel-information-transit';
/**
 * 
 * @export
 * @interface Ptsv2paymentsTravelInformation
 */
export interface Ptsv2paymentsTravelInformation {
    /**
     * Duration of the auto rental or lodging rental.  #### Auto rental This field is supported for Visa, MasterCard, and American Express. **Important** If this field is not included when the `processingInformation.industryDataType` is auto rental, the transaction is declined. 
     * @type {string}
     * @memberof Ptsv2paymentsTravelInformation
     */
    duration?: string;
    /**
     * 
     * @type {Ptsv2paymentsTravelInformationAgency}
     * @memberof Ptsv2paymentsTravelInformation
     */
    agency?: Ptsv2paymentsTravelInformationAgency;
    /**
     * 
     * @type {Ptsv2paymentsTravelInformationAutoRental}
     * @memberof Ptsv2paymentsTravelInformation
     */
    autoRental?: Ptsv2paymentsTravelInformationAutoRental;
    /**
     * 
     * @type {Ptsv2paymentsTravelInformationLodging}
     * @memberof Ptsv2paymentsTravelInformation
     */
    lodging?: Ptsv2paymentsTravelInformationLodging;
    /**
     * 
     * @type {Ptsv2paymentsTravelInformationTransit}
     * @memberof Ptsv2paymentsTravelInformation
     */
    transit?: Ptsv2paymentsTravelInformationTransit;
}
