/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Ptsv2paymentsProcessingInformationPurchaseOptions
 */
export interface Ptsv2paymentsProcessingInformationPurchaseOptions {
    /**
     * Flag that indicates whether this transaction is an EBT transaction. Possible values: - `true` - `false`  #### PIN debit Required field for EBT and EBT voucher transactions that use PIN debit credit or PIN debit purchase; otherwise, not used. 
     * @type {boolean}
     * @memberof Ptsv2paymentsProcessingInformationPurchaseOptions
     */
    isElectronicBenefitsTransfer?: boolean;
    /**
     * Flag that indicates an EBT voucher transaction. Possible value: - `EBT_VOUCHER`: Indicates the PIN debit transaction is an EBT voucher.  #### PIN debit Required field for EBT voucher transactions that use PIN debit purchase; otherwise, not used. 
     * @type {string}
     * @memberof Ptsv2paymentsProcessingInformationPurchaseOptions
     */
    type?: string;
}
