/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Ptsv2paymentsTokenInformationPaymentInstrument } from './ptsv2payments-token-information-payment-instrument';
import { Ptsv2paymentsTokenInformationShippingAddress } from './ptsv2payments-token-information-shipping-address';
/**
 * 
 * @export
 * @interface Ptsv2paymentsTokenInformation
 */
export interface Ptsv2paymentsTokenInformation {
    /**
     * TMS Transient Token, 64 hexadecimal id value representing captured payment credentials (including Sensitive Authentication Data, e.g. CVV). 
     * @type {string}
     * @memberof Ptsv2paymentsTokenInformation
     */
    jti?: string;
    /**
     * Flex API Transient Token encoded as JWT (JSON Web Token), e.g. Flex microform or Unified Payment checkout result. 
     * @type {string}
     * @memberof Ptsv2paymentsTokenInformation
     */
    transientTokenJwt?: string;
    /**
     * 
     * @type {Ptsv2paymentsTokenInformationPaymentInstrument}
     * @memberof Ptsv2paymentsTokenInformation
     */
    paymentInstrument?: Ptsv2paymentsTokenInformationPaymentInstrument;
    /**
     * 
     * @type {Ptsv2paymentsTokenInformationShippingAddress}
     * @memberof Ptsv2paymentsTokenInformation
     */
    shippingAddress?: Ptsv2paymentsTokenInformationShippingAddress;
    /**
     * Indicates whether a payment network token associated with a TMS token should be used for authorization. This field can contain one of following values:  - `ignore`: Use a tokenized card number for an authorization, even if the TMS token has an associated payment network token. - `prefer`: (Default) Use an associated payment network token for an authorization if the TMS token has one; otherwise, use the tokenized card number. 
     * @type {string}
     * @memberof Ptsv2paymentsTokenInformation
     */
    networkTokenOption?: string;
}
