/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Ptsv2paymentsMerchantInformationMerchantDescriptor
 */
export interface Ptsv2paymentsMerchantInformationMerchantDescriptor {
    /**
     * Your merchant name.  **Note** For Paymentech processor using Cybersource Payouts, the maximum data length is 22.  #### PIN debit Your business name. This name is displayed on the cardholder’s statement. When you include more than one consecutive space, extra spaces are removed.  When you do not include this value in your PIN debit request, the merchant name from your account is used. **Important** This value must consist of English characters.  Optional field for PIN debit credit or PIN debit purchase requests.  #### Airline processing Your merchant name. This name is displayed on the cardholder’s statement. When you include more than one consecutive space, extra spaces are removed.  **Note** Some airline fee programs may require the original ticket number (ticket identifier) or the ancillary service description in positions 13 through 23 of this field.  **Important** This value must consist of English characters.  Required for captures and credits. 
     * @type {string}
     * @memberof Ptsv2paymentsMerchantInformationMerchantDescriptor
     */
    name?: string;
    /**
     * An alternate name for the merchant.  For the descriptions, used-by information, data types, and lengths for these fields, see the `merchant_descriptor_alternate` field description in [Credit Card Services Using the SCMP API.](http://apps.cybersource.com/library/documentation/dev_guides/CC_Svcs_SCMP_API/html)--> 
     * @type {string}
     * @memberof Ptsv2paymentsMerchantInformationMerchantDescriptor
     */
    alternateName?: string;
    /**
     * For the descriptions, used-by information, data types, and lengths for these fields, see `merchant_descriptor_contact` field description in [Credit Card Services Using the SCMP API.](http://apps.cybersource.com/library/documentation/dev_guides/CC_Svcs_SCMP_API/html)--> Contact information for the merchant.  **Note** These are the maximum data lengths for the following payment processors: - FDCCompass (13) - Paymentech (13) 
     * @type {string}
     * @memberof Ptsv2paymentsMerchantInformationMerchantDescriptor
     */
    contact?: string;
    /**
     * First line of merchant's address. For the descriptions, used-by information, data types, and lengths for these fields, see `merchant_descriptor_street` field description in [Credit Card Services Using the SCMP API.](http://apps.cybersource.com/library/documentation/dev_guides/CC_Svcs_SCMP_API/html) 
     * @type {string}
     * @memberof Ptsv2paymentsMerchantInformationMerchantDescriptor
     */
    address1?: string;
    /**
     * Merchant's City.  #### PIN debit City for your business location. This value might be displayed on the cardholder’s statement.  When you do not include this value in your PIN debit request, the merchant name from your account is used. **Important** This value must consist of English characters.  Optional field for PIN debit credit or PIN debit purchase requests. 
     * @type {string}
     * @memberof Ptsv2paymentsMerchantInformationMerchantDescriptor
     */
    locality?: string;
    /**
     * Merchant's country.  #### PIN debit Country code for your business location. Use the [ISO Standard Country Codes](https://developer.cybersource.com/library/documentation/sbc/quickref/countries_alpha_list.pdf) This value might be displayed on the cardholder’s statement.  When you do not include this value in your PIN debit request, the merchant name from your account is used. **Important** This value must consist of English characters. **Note** If your business is located in the U.S. or Canada and you include this field in a request, you must also include `merchantInformation.merchantDescriptor.administrativeArea`.  Optional field for PIN debit credit or PIN debit purchase. 
     * @type {string}
     * @memberof Ptsv2paymentsMerchantInformationMerchantDescriptor
     */
    country?: string;
    /**
     * Merchant's postal code.  #### PIN debit Postal code for your business location. This value might be displayed on the cardholder’s statement.  If your business is domiciled in the U.S., you can use a 5-digit or 9-digit postal code. A 9-digit postal code must follow this format: [5 digits][dash][4 digits] Example: `12345-6789`  If your business is domiciled in Canada, you can use a 6-digit or 9-digit postal code. A 6-digit postal code must follow this format: [alpha][numeric][alpha][space] [numeric][alpha][numeric] Example: `A1B 2C3`  When you do not include this value in your PIN debit request, the merchant name from your account is used. **Important** This value must consist of English characters.  **Note** This field is supported only for businesses located in the U.S. or Canada. **Important** Mastercard requires a postal code for any country that uses postal codes. You can provide the postal code in your account or you can include this field in your request.  Optional field for PIN debit credit or PIN debit purchase. 
     * @type {string}
     * @memberof Ptsv2paymentsMerchantInformationMerchantDescriptor
     */
    postalCode?: string;
    /**
     * The state where the merchant is located.  #### PIN debit State code or region code for your business. Use the Use the [State, Province, and Territory Codes for the United States and Canada](https://developer.cybersource.com/library/documentation/sbc/quickref/states_and_provinces.pdf) This value might be displayed on the cardholder’s statement.  When you do not include this value in your PIN debit request, the merchant name from your account is used. **Important** This value must consist of English characters.  **Note** This field is supported only for businesses located in the U.S. or Canada.  Optional field for PIN debit credit or PIN debit purchase. 
     * @type {string}
     * @memberof Ptsv2paymentsMerchantInformationMerchantDescriptor
     */
    administrativeArea?: string;
    /**
     * Merchant phone as contact information for CNP transactions 
     * @type {string}
     * @memberof Ptsv2paymentsMerchantInformationMerchantDescriptor
     */
    phone?: string;
    /**
     * Address of company's website provided by merchant 
     * @type {string}
     * @memberof Ptsv2paymentsMerchantInformationMerchantDescriptor
     */
    url?: string;
    /**
     * #### Visa Platform Connect This field will indicate merchant country of origin 
     * @type {string}
     * @memberof Ptsv2paymentsMerchantInformationMerchantDescriptor
     */
    countryOfOrigin?: string;
}
