/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Ptsv2creditsProcessingInformationJapanPaymentOptions
 */
export interface Ptsv2creditsProcessingInformationJapanPaymentOptions {
    /**
     * This value is a 2-digit code indicating the payment method. Use Payment Method Code value that applies to the tranasction. - 10 (One-time payment) - 21, 22, 23, 24  (Bonus(one-time)payment) - 61 (Installment payment) - 31, 32, 33, 34  (Integrated (Bonus + Installment)payment) - 80 (Revolving payment) 
     * @type {string}
     * @memberof Ptsv2creditsProcessingInformationJapanPaymentOptions
     */
    paymentMethod?: string;
    /**
     * Number of Installments. 
     * @type {string}
     * @memberof Ptsv2creditsProcessingInformationJapanPaymentOptions
     */
    installments?: string;
}
