/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Ptsv2paymentsidcapturesDeviceInformation
 */
export interface Ptsv2paymentsidcapturesDeviceInformation {
    /**
     * DNS resolved hostname from `ipAddress`.
     * @type {string}
     * @memberof Ptsv2paymentsidcapturesDeviceInformation
     */
    hostName?: string;
    /**
     * IP address of the customer.  #### Used by **Authorization, Capture, and Credit** Optional field. 
     * @type {string}
     * @memberof Ptsv2paymentsidcapturesDeviceInformation
     */
    ipAddress?: string;
    /**
     * Customer’s browser as identified from the HTTP header data. For example, `Mozilla` is the value that identifies the Netscape browser. 
     * @type {string}
     * @memberof Ptsv2paymentsidcapturesDeviceInformation
     */
    userAgent?: string;
}
