/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Ptsv2paymentsPaymentInformationBankAccount
 */
export interface Ptsv2paymentsPaymentInformationBankAccount {
    /**
     * Account type.  Possible values:  - **C**: Checking.  - **G**: General ledger. This value is supported only on Wells Fargo ACH.  - **S**: Savings (U.S. dollars only).  - **X**: Corporate checking (U.S. dollars only). 
     * @type {string}
     * @memberof Ptsv2paymentsPaymentInformationBankAccount
     */
    type?: string;
    /**
     * Account number.  When processing encoded account numbers, use this field for the encoded account number. 
     * @type {string}
     * @memberof Ptsv2paymentsPaymentInformationBankAccount
     */
    number?: string;
    /**
     * Identifier for the bank that provided the customer’s encoded account number.  To obtain the bank identifier, contact your processor.  For details, see `account_encoder_id` request-level field description in [Credit Card Services Using the SCMP API.](https://apps.cybersource.com/library/documentation/dev_guides/CC_Svcs_SCMP_API/html/) 
     * @type {string}
     * @memberof Ptsv2paymentsPaymentInformationBankAccount
     */
    encoderId?: string;
    /**
     * Check number.  Chase Paymentech Solutions - Optional. CyberSource ACH Service - Not used. RBS WorldPay Atlanta - Optional on debits. Required on credits. TeleCheck - Strongly recommended on debit requests. Optional on credits. 
     * @type {string}
     * @memberof Ptsv2paymentsPaymentInformationBankAccount
     */
    checkNumber?: string;
    /**
     * Image reference number associated with the check. You cannot include any special characters. 
     * @type {string}
     * @memberof Ptsv2paymentsPaymentInformationBankAccount
     */
    checkImageReferenceNumber?: string;
}
