/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Ptsv2paymentsPaymentInformationInstrumentIdentifier
 */
export interface Ptsv2paymentsPaymentInformationInstrumentIdentifier {
    /**
     * Unique identifier for the Instrument Identifier token used in the transaction. When you include this value in your request, many of the fields that can be supplied for an authorization or credit become optional. 
     * @type {string}
     * @memberof Ptsv2paymentsPaymentInformationInstrumentIdentifier
     */
    id?: string;
}
