/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReportingV3ChargebackDetailsGet200Response
 */
export interface ReportingV3ChargebackDetailsGet200Response {
    /**
     * Organization Id
     * @type {string}
     * @memberof ReportingV3ChargebackDetailsGet200Response
     */
    organizationId?: string;
    /**
     * Report Start Date (ISO 8601 Extended)
     * @type {Date}
     * @memberof ReportingV3ChargebackDetailsGet200Response
     */
    startTime?: Date;
    /**
     * Report Start Date (ISO 8601 Extended)
     * @type {Date}
     * @memberof ReportingV3ChargebackDetailsGet200Response
     */
    endTime?: Date;
    /**
     * List of Chargeback Details list.
     * @type {Array<any>}
     * @memberof ReportingV3ChargebackDetailsGet200Response
     */
    chargebackDetails?: Array<any>;
}
