/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
 */
export interface ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries {
    /**
     * 
     * @type {string}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    paymentSubTypeDescription?: string;
    /**
     * 
     * @type {Date}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    endTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    salesCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    salesAmount?: string;
    /**
     * 
     * @type {number}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    creditCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    creditAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    accountName?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    merchantId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReportingV3PaymentBatchSummariesGet200ResponsePaymentBatchSummaries
     */
    merchantName?: string;
}
