/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReportingV3PurchaseRefundDetailsGet200Response
 */
export interface ReportingV3PurchaseRefundDetailsGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ReportingV3PurchaseRefundDetailsGet200Response
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportingV3PurchaseRefundDetailsGet200Response
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ReportingV3PurchaseRefundDetailsGet200Response
     */
    pageResults?: number;
    /**
     * List of Request Info values
     * @type {Array<any>}
     * @memberof ReportingV3PurchaseRefundDetailsGet200Response
     */
    requestDetails?: Array<any>;
    /**
     * List of Settlement Info values
     * @type {Array<any>}
     * @memberof ReportingV3PurchaseRefundDetailsGet200Response
     */
    settlements?: Array<any>;
    /**
     * List of Authorization Info values
     * @type {Array<any>}
     * @memberof ReportingV3PurchaseRefundDetailsGet200Response
     */
    authorizations?: Array<any>;
    /**
     * List of Fee Funding Info values
     * @type {Array<any>}
     * @memberof ReportingV3PurchaseRefundDetailsGet200Response
     */
    feeAndFundingDetails?: Array<any>;
    /**
     * List of Other Info values
     * @type {Array<any>}
     * @memberof ReportingV3PurchaseRefundDetailsGet200Response
     */
    others?: Array<any>;
    /**
     * List of Settlement Status Info values
     * @type {Array<any>}
     * @memberof ReportingV3PurchaseRefundDetailsGet200Response
     */
    settlementStatuses?: Array<any>;
}
