/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Provides failed validation input field detail 
 * @export
 * @interface ReportingV3ReportSubscriptionsNameDelete400ResponseDetails
 */
export interface ReportingV3ReportSubscriptionsNameDelete400ResponseDetails {
    /**
     * Field in request that caused an error 
     * @type {string}
     * @memberof ReportingV3ReportSubscriptionsNameDelete400ResponseDetails
     */
    field?: string;
    /**
     * Documented reason code 
     * @type {string}
     * @memberof ReportingV3ReportSubscriptionsNameDelete400ResponseDetails
     */
    reason?: string;
}
