/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Notification Of Change
 * @export
 * @interface ReportingV3NotificationofChangesGet200ResponseNotificationOfChanges
 */
export interface ReportingV3NotificationofChangesGet200ResponseNotificationOfChanges {
    /**
     * Merchant Reference Number
     * @type {string}
     * @memberof ReportingV3NotificationofChangesGet200ResponseNotificationOfChanges
     */
    merchantReferenceNumber?: string;
    /**
     * Transaction Reference Number
     * @type {string}
     * @memberof ReportingV3NotificationofChangesGet200ResponseNotificationOfChanges
     */
    transactionReferenceNumber?: string;
    /**
     * Notification Of Change Date(ISO 8601 Extended)
     * @type {Date}
     * @memberof ReportingV3NotificationofChangesGet200ResponseNotificationOfChanges
     */
    time?: Date;
    /**
     * Merchant Reference Number
     * @type {string}
     * @memberof ReportingV3NotificationofChangesGet200ResponseNotificationOfChanges
     */
    code?: string;
    /**
     * Account Type
     * @type {string}
     * @memberof ReportingV3NotificationofChangesGet200ResponseNotificationOfChanges
     */
    accountType?: string;
    /**
     * Routing Number
     * @type {string}
     * @memberof ReportingV3NotificationofChangesGet200ResponseNotificationOfChanges
     */
    routingNumber?: string;
    /**
     * Account Number
     * @type {string}
     * @memberof ReportingV3NotificationofChangesGet200ResponseNotificationOfChanges
     */
    accountNumber?: string;
    /**
     * Consumer Name
     * @type {string}
     * @memberof ReportingV3NotificationofChangesGet200ResponseNotificationOfChanges
     */
    consumerName?: string;
}
