/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReportingV3NetFundingsGet200ResponseNetFundingSummaries } from './reporting-v3-net-fundings-get200-response-net-funding-summaries';
import { ReportingV3NetFundingsGet200ResponseTotalPurchases } from './reporting-v3-net-fundings-get200-response-total-purchases';
/**
 * 
 * @export
 * @interface ReportingV3NetFundingsGet200Response
 */
export interface ReportingV3NetFundingsGet200Response {
    /**
     * Valid report Start Date in **ISO 8601 format**. Please refer the following link to know more about ISO 8601 format.[Rfc Date Format](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14)  **Example:** - yyyy-MM-dd'T'HH:mm:ss.SSSZZ 
     * @type {Date}
     * @memberof ReportingV3NetFundingsGet200Response
     */
    startTime?: Date;
    /**
     * Valid report End Date in **ISO 8601 format** **Example date format:** - yyyy-MM-dd'T'HH:mm:ss.SSSZZ 
     * @type {Date}
     * @memberof ReportingV3NetFundingsGet200Response
     */
    endTime?: Date;
    /**
     * List of Netfunding summary objects
     * @type {Array<ReportingV3NetFundingsGet200ResponseNetFundingSummaries>}
     * @memberof ReportingV3NetFundingsGet200Response
     */
    netFundingSummaries?: Array<ReportingV3NetFundingsGet200ResponseNetFundingSummaries>;
    /**
     * List of total purchases currency wise
     * @type {Array<ReportingV3NetFundingsGet200ResponseTotalPurchases>}
     * @memberof ReportingV3NetFundingsGet200Response
     */
    totalPurchases?: Array<ReportingV3NetFundingsGet200ResponseTotalPurchases>;
    /**
     * List of total refunds currency wise
     * @type {Array<ReportingV3NetFundingsGet200ResponseTotalPurchases>}
     * @memberof ReportingV3NetFundingsGet200Response
     */
    totalRefunds?: Array<ReportingV3NetFundingsGet200ResponseTotalPurchases>;
    /**
     * List of total fees currency wise
     * @type {Array<ReportingV3NetFundingsGet200ResponseTotalPurchases>}
     * @memberof ReportingV3NetFundingsGet200Response
     */
    totalFees?: Array<ReportingV3NetFundingsGet200ResponseTotalPurchases>;
    /**
     * List of total chargebacks currency wise
     * @type {Array<ReportingV3NetFundingsGet200ResponseTotalPurchases>}
     * @memberof ReportingV3NetFundingsGet200Response
     */
    totalChargebacks?: Array<ReportingV3NetFundingsGet200ResponseTotalPurchases>;
    /**
     * List of new total currency wise
     * @type {Array<ReportingV3NetFundingsGet200ResponseTotalPurchases>}
     * @memberof ReportingV3NetFundingsGet200Response
     */
    netTotal?: Array<ReportingV3NetFundingsGet200ResponseTotalPurchases>;
}
