/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
 */
export interface ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails {
    /**
     * Processor Merchant Id
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    processorMerchantId?: string;
    /**
     * Merchant Name
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    merchantName?: string;
    /**
     * Transaction Reference Number
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    transactionReferenceNumber?: string;
    /**
     * Merchant Reference Number
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    merchantReferenceNumber?: string;
    /**
     * Nature of Dispute
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    natureOfDispute?: string;
    /**
     * Retrieval Alert Type
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    alertType?: string;
    /**
     * Retrieval Amount
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    amount?: string;
    /**
     * Retrieval Sign
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    sign?: string;
    /**
     * Retrieval Action
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    action?: string;
    /**
     * Card Type
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    cardType?: string;
    /**
     * Original Settlement Date
     * @type {Date}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    originalSettlementTime?: Date;
    /**
     * Tracking Number
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    trackingNumber?: string;
    /**
     * Valid ISO 4217 ALPHA-3 currency code
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    currencyCode?: string;
    /**
     * Request Id
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    requestId?: string;
    /**
     * Response Due Date
     * @type {Date}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    responseDueTime?: Date;
    /**
     * Retrieval Date
     * @type {Date}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    time?: Date;
    /**
     * Retrieval Action Description
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    actionDescription?: string;
    /**
     * Customer Id
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    customerId?: string;
    /**
     * Retrieval Reason Code
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    reasonCode?: string;
    /**
     * Representment CP Date
     * @type {Date}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    representmentCPTime?: Date;
    /**
     * ICS Request Applications
     * @type {string}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    applications?: string;
    /**
     * Event Request Date
     * @type {Date}
     * @memberof ReportingV3RetrievalDetailsGet200ResponseRetrievalDetails
     */
    eventRequestedTime?: Date;
}
