/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Reportingv3reportsReportPreferences } from './reportingv3reports-report-preferences';
/**
 * 
 * @export
 * @interface ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings
 */
export interface ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings {
    /**
     * Report Format Valid values:   - application/xml   - text/csv 
     * @type {string}
     * @memberof ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings
     */
    reportMimeType?: string;
    /**
     * Report Frequency Value Valid Values:   - DAILY   - WEEKLY   - MONTHLY   - ADHOC 
     * @type {string}
     * @memberof ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings
     */
    reportFrequency?: string;
    /**
     * Report Name
     * @type {string}
     * @memberof ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings
     */
    reportName?: string;
    /**
     * Time Zone
     * @type {string}
     * @memberof ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings
     */
    timezone?: string;
    /**
     * Start Time
     * @type {string}
     * @memberof ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings
     */
    startTime?: string;
    /**
     * Start Day
     * @type {number}
     * @memberof ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings
     */
    startDay?: number;
    /**
     * List of filters to apply
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings
     */
    reportFilters?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {Reportingv3reportsReportPreferences}
     * @memberof ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings
     */
    reportPreferences?: Reportingv3reportsReportPreferences;
}
