/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReportingV3NotificationofChangesGet200Response
 */
export interface ReportingV3NotificationofChangesGet200Response {
    /**
     * List of Notification Of Change Info values
     * @type {Array<any>}
     * @memberof ReportingV3NotificationofChangesGet200Response
     */
    notificationOfChanges?: Array<any>;
}
