/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RiskV1AuthenticationSetupsPost201ResponseConsumerAuthenticationInformation
 */
export interface RiskV1AuthenticationSetupsPost201ResponseConsumerAuthenticationInformation {
    /**
     * JSON Web Token (JWT) used to authenticate the consumer with the authentication provider, such as, CardinalCommerce or Rupay. Note - Max Length of this field is 2048 characters. 
     * @type {string}
     * @memberof RiskV1AuthenticationSetupsPost201ResponseConsumerAuthenticationInformation
     */
    accessToken?: string;
    /**
     * This identifier represents cardinal has started device data collection session and this must be passed in Authentication JWT to Cardinal when invoking the deviceDataCollectionUrl. 
     * @type {string}
     * @memberof RiskV1AuthenticationSetupsPost201ResponseConsumerAuthenticationInformation
     */
    referenceId?: string;
    /**
     * The deviceDataCollectionUrl is the location to send the Authentication JWT when invoking the Device Data collection process. 
     * @type {string}
     * @memberof RiskV1AuthenticationSetupsPost201ResponseConsumerAuthenticationInformation
     */
    deviceDataCollectionUrl?: string;
}
