/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList } from './risk-v1-export-compliance-inquiries-post201-response-export-compliance-information-watch-list';
/**
 * 
 * @export
 * @interface RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformation
 */
export interface RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformation {
    /**
     * Likelihood that the country associated with the customer’s IP address was identified correctly. Returns a value from 1–100, where 100 indicates the highest likelihood. If the country cannot be determined, the value is –1. 
     * @type {number}
     * @memberof RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformation
     */
    ipCountryConfidence?: number;
    /**
     * Returned when the Denied Parties List check (first two codes) or the export service (all others) would have declined the transaction. This field can contain one or more of these values: - `MATCH-DPC`: Denied Parties List match. - `UNV-DPC`: Denied Parties List unavailable. - `MATCH-BCO`: Billing country restricted. - `MATCH-EMCO`: Email country restricted. - `MATCH-HCO`: Host name country restricted. - `MATCH-IPCO`: IP country restricted. - `MATCH-SCO`: Shipping country restricted. 
     * @type {Array<string>}
     * @memberof RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformation
     */
    infoCodes?: Array<string>;
    /**
     * 
     * @type {RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList}
     * @memberof RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformation
     */
    watchList?: RiskV1ExportComplianceInquiriesPost201ResponseExportComplianceInformationWatchList;
}
