/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RiskV1AuthenticationSetupsPost201ResponseErrorInformationDetails } from './risk-v1-authentication-setups-post201-response-error-information-details';
/**
 * 
 * @export
 * @interface RiskV1AddressVerificationsPost201ResponseErrorInformation
 */
export interface RiskV1AddressVerificationsPost201ResponseErrorInformation {
    /**
     * The reason of the status. Value can be   - `APARTMENT_NUMBER_NOT_FOUND`   - `INSUFFICIENT_ADDRESS_INFORMATION`   - `HOUSE_OR_BOX_NUMBER_NOT_FOUND`   - `MULTIPLE_ADDRESS_MATCHES`   - `BOX_NUMBER_NOT_FOUND`   - `ROUTE_SERVICE_NOT_FOUND`   - `STREET_NAME_NOT_FOUND`   - `POSTAL_CODE_NOT_FOUND`   - `UNVERIFIABLE_ADDRESS`   - `MULTIPLE_ADDRESS_MATCHES_INTERNATIONAL`   - `ADDRESS_MATCH_NOT_FOUND`   - `UNSUPPORTED_CHARACTER_SET`   - `INVALID_MERCHANT_CONFIGURATION` 
     * @type {string}
     * @memberof RiskV1AddressVerificationsPost201ResponseErrorInformation
     */
    reason?: string;
    /**
     * The detail message related to the status and reason listed above.
     * @type {string}
     * @memberof RiskV1AddressVerificationsPost201ResponseErrorInformation
     */
    message?: string;
    /**
     * 
     * @type {Array<RiskV1AuthenticationSetupsPost201ResponseErrorInformationDetails>}
     * @memberof RiskV1AddressVerificationsPost201ResponseErrorInformation
     */
    details?: Array<RiskV1AuthenticationSetupsPost201ResponseErrorInformationDetails>;
}
