/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RiskV1DecisionsPost201ResponseRiskInformationProfile
 */
export interface RiskV1DecisionsPost201ResponseRiskInformationProfile {
    /**
     * Name of the active profile chosen by the profile selector. If no profile selector exists, the default active profile is chosen.  **Note** By default, your default profile is the active profile, or the Profile Selector chooses the active profile. Use this field only if you want to specify the name of a different profile. The passed-in profile will then become the active profile. 
     * @type {string}
     * @memberof RiskV1DecisionsPost201ResponseRiskInformationProfile
     */
    name?: string;
    /**
     * Name of the queue where orders that are not automatically accepted are sent. 
     * @type {string}
     * @memberof RiskV1DecisionsPost201ResponseRiskInformationProfile
     */
    desinationQueue?: string;
    /**
     * Name of the profile selector rule that chooses the profile to use for the transaction. If no profile selector exists, the value is Default Active Profile. 
     * @type {string}
     * @memberof RiskV1DecisionsPost201ResponseRiskInformationProfile
     */
    selectorRule?: string;
}
