/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PtsV2RefundsVoidsPost201ResponseLinks } from './pts-v2-refunds-voids-post201-response-links';
import { RiskV1AddressVerificationsPost201ResponseAddressVerificationInformation } from './risk-v1-address-verifications-post201-response-address-verification-information';
import { RiskV1AddressVerificationsPost201ResponseErrorInformation } from './risk-v1-address-verifications-post201-response-error-information';
import { RiskV1AuthenticationSetupsPost201ResponseClientReferenceInformation } from './risk-v1-authentication-setups-post201-response-client-reference-information';
/**
 * 
 * @export
 * @interface RiskV1AddressVerificationsPost201Response
 */
export interface RiskV1AddressVerificationsPost201Response {
    /**
     * 
     * @type {PtsV2RefundsVoidsPost201ResponseLinks}
     * @memberof RiskV1AddressVerificationsPost201Response
     */
    links?: PtsV2RefundsVoidsPost201ResponseLinks;
    /**
     * An unique identification number generated by Cybersource to identify the submitted request. Returned by all services. It is also appended to the endpoint of the resource. On incremental authorizations, this value with be the same as the identification number returned in the original authorization response. 
     * @type {string}
     * @memberof RiskV1AddressVerificationsPost201Response
     */
    id?: string;
    /**
     * Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ` **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.). The `T` separates the date and the time. The `Z` indicates UTC.  Returned by Cybersource for all services. 
     * @type {string}
     * @memberof RiskV1AddressVerificationsPost201Response
     */
    submitTimeUtc?: string;
    /**
     * Time that the transaction was submitted in local time. Generated by Cybersource.
     * @type {string}
     * @memberof RiskV1AddressVerificationsPost201Response
     */
    submitTimeLocal?: string;
    /**
     * The status for the call can be: - COMPLETED - INVALID_REQUEST - DECLINED 
     * @type {string}
     * @memberof RiskV1AddressVerificationsPost201Response
     */
    status?: string;
    /**
     * The message describing the reason of the status. Value can be   - Apartment number missing or not found.   - Insufficient address information.   - House/Box number not found on street.   - Multiple address matches were found.   - P.O. Box identifier not found or out of range.   - Route service identifier not found or out of range.   - Street name not found in Postal code.   - Postal code not found in database.   - Unable to verify or correct address.   - Multiple addres matches were found (international)   - Address match not found (no reason given)   - Unsupported character set 
     * @type {string}
     * @memberof RiskV1AddressVerificationsPost201Response
     */
    message?: string;
    /**
     * 
     * @type {RiskV1AuthenticationSetupsPost201ResponseClientReferenceInformation}
     * @memberof RiskV1AddressVerificationsPost201Response
     */
    clientReferenceInformation?: RiskV1AuthenticationSetupsPost201ResponseClientReferenceInformation;
    /**
     * 
     * @type {RiskV1AddressVerificationsPost201ResponseAddressVerificationInformation}
     * @memberof RiskV1AddressVerificationsPost201Response
     */
    addressVerificationInformation?: RiskV1AddressVerificationsPost201ResponseAddressVerificationInformation;
    /**
     * 
     * @type {RiskV1AddressVerificationsPost201ResponseErrorInformation}
     * @memberof RiskV1AddressVerificationsPost201Response
     */
    errorInformation?: RiskV1AddressVerificationsPost201ResponseErrorInformation;
}
