/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RiskV1ExportComplianceInquiriesPost201Response
 */
export interface RiskV1ExportComplianceInquiriesPost201Response {
    /**
     * 
     * @type {any}
     * @memberof RiskV1ExportComplianceInquiriesPost201Response
     */
    links?: any;
    /**
     * An unique identification number generated by Cybersource to identify the submitted request. Returned by all services. It is also appended to the endpoint of the resource. On incremental authorizations, this value with be the same as the identification number returned in the original authorization response. 
     * @type {string}
     * @memberof RiskV1ExportComplianceInquiriesPost201Response
     */
    id?: string;
    /**
     * Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ` **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.). The `T` separates the date and the time. The `Z` indicates UTC.  Returned by Cybersource for all services. 
     * @type {string}
     * @memberof RiskV1ExportComplianceInquiriesPost201Response
     */
    submitTimeUtc?: string;
    /**
     * Time that the transaction was submitted in local time. Generated by Cybersource.
     * @type {string}
     * @memberof RiskV1ExportComplianceInquiriesPost201Response
     */
    submitTimeLocal?: string;
    /**
     * The status for the call can be: - COMPLETED - INVALID_REQUEST - DECLINED 
     * @type {string}
     * @memberof RiskV1ExportComplianceInquiriesPost201Response
     */
    status?: string;
    /**
     * The message describing the reason of the status. Value can be   - The customer matched the Denied Parties List   - The Export bill_country/ship_country  match   - Export email_country match   - Export hostname_country/ip_country match 
     * @type {string}
     * @memberof RiskV1ExportComplianceInquiriesPost201Response
     */
    message?: string;
    /**
     * 
     * @type {any}
     * @memberof RiskV1ExportComplianceInquiriesPost201Response
     */
    clientReferenceInformation?: any;
    /**
     * 
     * @type {any}
     * @memberof RiskV1ExportComplianceInquiriesPost201Response
     */
    exportComplianceInformation?: any;
    /**
     * 
     * @type {any}
     * @memberof RiskV1ExportComplianceInquiriesPost201Response
     */
    errorInformation?: any;
}
