/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PtsV2RefundsVoidsPost201ResponseLinks } from './pts-v2-refunds-voids-post201-response-links';
import { RiskV1AuthenticationSetupsPost201ResponseClientReferenceInformation } from './risk-v1-authentication-setups-post201-response-client-reference-information';
/**
 * 
 * @export
 * @interface RiskV1UpdatePost201Response
 */
export interface RiskV1UpdatePost201Response {
    /**
     * 
     * @type {PtsV2RefundsVoidsPost201ResponseLinks}
     * @memberof RiskV1UpdatePost201Response
     */
    links?: PtsV2RefundsVoidsPost201ResponseLinks;
    /**
     * 
     * @type {RiskV1AuthenticationSetupsPost201ResponseClientReferenceInformation}
     * @memberof RiskV1UpdatePost201Response
     */
    clientReferenceInformaton?: RiskV1AuthenticationSetupsPost201ResponseClientReferenceInformation;
    /**
     * An unique identification number generated by Cybersource to identify the submitted request. Returned by all services. It is also appended to the endpoint of the resource. On incremental authorizations, this value with be the same as the identification number returned in the original authorization response. 
     * @type {string}
     * @memberof RiskV1UpdatePost201Response
     */
    id?: string;
    /**
     * The status for risk update 201 calls. Possible values are: - INVALID_REQUEST - COMPLETED 
     * @type {string}
     * @memberof RiskV1UpdatePost201Response
     */
    status?: string;
    /**
     * Time of request in UTC. Format: `YYYY-MM-DDThh:mm:ssZ` **Example** `2016-08-11T22:47:57Z` equals August 11, 2016, at 22:47:57 (10:47:57 p.m.). The `T` separates the date and the time. The `Z` indicates UTC.  Returned by Cybersource for all services. 
     * @type {string}
     * @memberof RiskV1UpdatePost201Response
     */
    submitTimeUtc?: string;
}
