/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Customer's bank account details
 * @export
 * @interface Riskv1liststypeentriesPaymentInformationBank
 */
export interface Riskv1liststypeentriesPaymentInformationBank {
    /**
     * Customer's bank account number. You can use this field only when scoring a direct debit transaction. Use this field if you do not or are not allowed to provide the IBAN. Note Do not use the IBAN in this field. Use nly the traditional account number information. For the IBAN, use bank_iban. 
     * @type {string}
     * @memberof Riskv1liststypeentriesPaymentInformationBank
     */
    accountNumber?: string;
    /**
     * Country-specific code used to identify the customer’s bank. Required for some countries if you do not or are not allowed to provide the IBAN instead. You can use this field only when scoring a direct debit transaction. For specific requirements, see \"Required Bank Account Information by Country,\" 
     * @type {string}
     * @memberof Riskv1liststypeentriesPaymentInformationBank
     */
    code?: string;
    /**
     * Country where the bank is located. Use the two-character ISO codes. You can use this field only when scoring a direct debit transaction. 
     * @type {string}
     * @memberof Riskv1liststypeentriesPaymentInformationBank
     */
    country?: string;
    /**
     * International Bank Account Number (IBAN) for the bank account. For some countries you can provide this number instead of the traditional bank account information. You can use this field only when scoring a direct debit transaction. For specific requirements, see \"Required Bank Account Information by Country,\" 
     * @type {string}
     * @memberof Riskv1liststypeentriesPaymentInformationBank
     */
    iban?: string;
}
