/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RiskV1AuthenticationSetupsPost201ResponseErrorInformationDetails } from './risk-v1-authentication-setups-post201-response-error-information-details';
/**
 * 
 * @export
 * @interface RiskV1AuthenticationSetupsPost201ResponseErrorInformation
 */
export interface RiskV1AuthenticationSetupsPost201ResponseErrorInformation {
    /**
     * The reason of the status.  Possible values:  - EXPIRED_CARD  - GENERAL_DECLINE 
     * @type {string}
     * @memberof RiskV1AuthenticationSetupsPost201ResponseErrorInformation
     */
    reason?: string;
    /**
     * The detail message related to the status and reason listed above.
     * @type {string}
     * @memberof RiskV1AuthenticationSetupsPost201ResponseErrorInformation
     */
    message?: string;
    /**
     * 
     * @type {Array<RiskV1AuthenticationSetupsPost201ResponseErrorInformationDetails>}
     * @memberof RiskV1AuthenticationSetupsPost201ResponseErrorInformation
     */
    details?: Array<RiskV1AuthenticationSetupsPost201ResponseErrorInformationDetails>;
}
