/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Riskv1exportcomplianceinquiriesOrderInformationBillTo } from './riskv1exportcomplianceinquiries-order-information-bill-to';
import { Riskv1exportcomplianceinquiriesOrderInformationLineItems } from './riskv1exportcomplianceinquiries-order-information-line-items';
import { Riskv1exportcomplianceinquiriesOrderInformationShipTo } from './riskv1exportcomplianceinquiries-order-information-ship-to';
/**
 * 
 * @export
 * @interface Riskv1exportcomplianceinquiriesOrderInformation
 */
export interface Riskv1exportcomplianceinquiriesOrderInformation {
    /**
     * 
     * @type {Riskv1exportcomplianceinquiriesOrderInformationBillTo}
     * @memberof Riskv1exportcomplianceinquiriesOrderInformation
     */
    billTo?: Riskv1exportcomplianceinquiriesOrderInformationBillTo;
    /**
     * 
     * @type {Riskv1exportcomplianceinquiriesOrderInformationShipTo}
     * @memberof Riskv1exportcomplianceinquiriesOrderInformation
     */
    shipTo?: Riskv1exportcomplianceinquiriesOrderInformationShipTo;
    /**
     * 
     * @type {Array<Riskv1exportcomplianceinquiriesOrderInformationLineItems>}
     * @memberof Riskv1exportcomplianceinquiriesOrderInformation
     */
    lineItems?: Array<Riskv1exportcomplianceinquiriesOrderInformationLineItems>;
}
