/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Riskv1exportcomplianceinquiriesExportComplianceInformationWeights } from './riskv1exportcomplianceinquiries-export-compliance-information-weights';
/**
 * 
 * @export
 * @interface Riskv1exportcomplianceinquiriesExportComplianceInformation
 */
export interface Riskv1exportcomplianceinquiriesExportComplianceInformation {
    /**
     * Parts of the customer’s information that must match with an entry in the DPL (denied parties list) before a match occurs. This field can contain one of the following values: - AND: (default) The customer’s name or company and the customer’s address must appear in the database. - OR: The customer’s name must appear in the database. - IGNORE: You want the service to detect a match only of the customer’s name or company but not of the address. 
     * @type {string}
     * @memberof Riskv1exportcomplianceinquiriesExportComplianceInformation
     */
    addressOperator?: string;
    /**
     * 
     * @type {Riskv1exportcomplianceinquiriesExportComplianceInformationWeights}
     * @memberof Riskv1exportcomplianceinquiriesExportComplianceInformation
     */
    weights?: Riskv1exportcomplianceinquiriesExportComplianceInformationWeights;
    /**
     * Use this field to specify which list(s) you want checked with the request. The reply will include the list name as well as the response data. To check against multiple lists, enter multiple list codes separated by a caret (^). For more information, see \"Restricted and Denied Parties List,\" page 68. 
     * @type {Array<string>}
     * @memberof Riskv1exportcomplianceinquiriesExportComplianceInformation
     */
    sanctionLists?: Array<string>;
}
