/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RiskV1DecisionsPost201ResponseRiskInformationTravelLastDestination
 */
export interface RiskV1DecisionsPost201ResponseRiskInformationTravelLastDestination {
    /**
     * Country of last destination on the route.
     * @type {string}
     * @memberof RiskV1DecisionsPost201ResponseRiskInformationTravelLastDestination
     */
    country?: string;
    /**
     * City of last destination on the route.
     * @type {string}
     * @memberof RiskV1DecisionsPost201ResponseRiskInformationTravelLastDestination
     */
    locality?: string;
    /**
     * Latitude of last destination on the route.
     * @type {string}
     * @memberof RiskV1DecisionsPost201ResponseRiskInformationTravelLastDestination
     */
    latitude?: string;
    /**
     * Longitude of last destination on the route.
     * @type {string}
     * @memberof RiskV1DecisionsPost201ResponseRiskInformationTravelLastDestination
     */
    longitude?: string;
}
