/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Riskv1exportcomplianceinquiriesOrderInformationBillToCompany
 */
export interface Riskv1exportcomplianceinquiriesOrderInformationBillToCompany {
    /**
     * Company name of person buying the product. Important: This field or billTo.firstName and billTo.lastName must be present. Else, your request will fail. 
     * @type {string}
     * @memberof Riskv1exportcomplianceinquiriesOrderInformationBillToCompany
     */
    name?: string;
}
