/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Riskv1decisionsTravelInformationLegs } from './riskv1decisions-travel-information-legs';
import { Riskv1decisionsTravelInformationPassengers } from './riskv1decisions-travel-information-passengers';
/**
 * 
 * @export
 * @interface Riskv1authenticationsTravelInformation
 */
export interface Riskv1authenticationsTravelInformation {
    /**
     * 
     * @type {Array<Riskv1decisionsTravelInformationLegs>}
     * @memberof Riskv1authenticationsTravelInformation
     */
    legs?: Array<Riskv1decisionsTravelInformationLegs>;
    /**
     * Number of passengers for whom the ticket was issued. If you do not include this field in your request, CyberSource uses a default value of 1. Required for American Express SafeKey (U.S.) for travel-related requests. 
     * @type {number}
     * @memberof Riskv1authenticationsTravelInformation
     */
    numberOfPassengers?: number;
    /**
     * 
     * @type {Array<Riskv1decisionsTravelInformationPassengers>}
     * @memberof Riskv1authenticationsTravelInformation
     */
    passengers?: Array<Riskv1decisionsTravelInformationPassengers>;
}
