/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
 */
export interface Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo {
    /**
     * Customer’s first name. This name must be the same as the name on the card. 
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
     */
    firstName?: string;
    /**
     * Customer’s last name. This name must be the same as the name on the card. 
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
     */
    lastName?: string;
    /**
     * Name of the customer’s company. 
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
     */
    company?: string;
    /**
     * Payment card billing street address as it appears on the credit card issuer’s records. 
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
     */
    address1?: string;
    /**
     * Additional address information. 
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
     */
    address2?: string;
    /**
     * Payment card billing city. 
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
     */
    locality?: string;
    /**
     * State or province of the billing address. Use the State, Province, and Territory Codes for the United States and Canada. 
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
     */
    administrativeArea?: string;
    /**
     * Postal code for the billing address. The postal code must consist of 5 to 9 digits.  When the billing country is the U.S., the 9-digit postal code must follow this format: [5 digits][dash][4 digits]  **Example** `12345-6789`  When the billing country is Canada, the 6-digit postal code must follow this format: [alpha][numeric][alpha][space][numeric][alpha][numeric]  **Example** `A1B 2C3` 
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
     */
    postalCode?: string;
    /**
     * Payment card billing country. Use the two-character ISO Standard Country Codes. 
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
     */
    country?: string;
    /**
     * Customer's email address, including the full domain name. 
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
     */
    email?: string;
    /**
     * Customer’s phone number. 
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultPaymentInstrumentBillTo
     */
    phoneNumber?: string;
}
