/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Tmsv2customersEmbeddedDefaultShippingAddressLinks } from './tmsv2customers-embedded-default-shipping-address-links';
import { Tmsv2customersEmbeddedDefaultShippingAddressMetadata } from './tmsv2customers-embedded-default-shipping-address-metadata';
import { Tmsv2customersEmbeddedDefaultShippingAddressShipTo } from './tmsv2customers-embedded-default-shipping-address-ship-to';
/**
 * 
 * @export
 * @interface Tmsv2customersEmbeddedDefaultShippingAddress
 */
export interface Tmsv2customersEmbeddedDefaultShippingAddress {
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultShippingAddressLinks}
     * @memberof Tmsv2customersEmbeddedDefaultShippingAddress
     */
    links?: Tmsv2customersEmbeddedDefaultShippingAddressLinks;
    /**
     * The id of the Shipping Address Token.
     * @type {string}
     * @memberof Tmsv2customersEmbeddedDefaultShippingAddress
     */
    id?: string;
    /**
     * Flag that indicates whether customer shipping address is the dafault. Valid values:  - `true`: Shipping Address is customer's default.  - `false`: Shipping Address is not customer's default. 
     * @type {boolean}
     * @memberof Tmsv2customersEmbeddedDefaultShippingAddress
     */
    _default?: boolean;
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultShippingAddressShipTo}
     * @memberof Tmsv2customersEmbeddedDefaultShippingAddress
     */
    shipTo?: Tmsv2customersEmbeddedDefaultShippingAddressShipTo;
    /**
     * 
     * @type {Tmsv2customersEmbeddedDefaultShippingAddressMetadata}
     * @memberof Tmsv2customersEmbeddedDefaultShippingAddress
     */
    metadata?: Tmsv2customersEmbeddedDefaultShippingAddressMetadata;
}
