/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Tmsv2customersBuyerInformation
 */
export interface Tmsv2customersBuyerInformation {
    /**
     * Your identifier for the customer. 
     * @type {string}
     * @memberof Tmsv2customersBuyerInformation
     */
    merchantCustomerID?: string;
    /**
     * Customer's primary email address, including the full domain name. 
     * @type {string}
     * @memberof Tmsv2customersBuyerInformation
     */
    email?: string;
}
