/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TssV2TransactionsPost201ResponseEmbeddedPaymentInformationBankAccount } from './tss-v2-transactions-post201-response-embedded-payment-information-bank-account';
/**
 * 
 * @export
 * @interface TssV2TransactionsPost201ResponseEmbeddedPaymentInformationBank
 */
export interface TssV2TransactionsPost201ResponseEmbeddedPaymentInformationBank {
    /**
     * 
     * @type {TssV2TransactionsPost201ResponseEmbeddedPaymentInformationBankAccount}
     * @memberof TssV2TransactionsPost201ResponseEmbeddedPaymentInformationBank
     */
    account?: TssV2TransactionsPost201ResponseEmbeddedPaymentInformationBankAccount;
}
