/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TssV2TransactionsPost201ResponseEmbeddedPaymentInformationBankAccount
 */
export interface TssV2TransactionsPost201ResponseEmbeddedPaymentInformationBankAccount {
    /**
     * Last four digits of the customer’s payment account number. 
     * @type {string}
     * @memberof TssV2TransactionsPost201ResponseEmbeddedPaymentInformationBankAccount
     */
    suffix?: string;
    /**
     * Bank Identification Number (BIN). This is the initial four to six numbers on a credit card account number. 
     * @type {string}
     * @memberof TssV2TransactionsPost201ResponseEmbeddedPaymentInformationBankAccount
     */
    prefix?: string;
}
