/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TssV2TransactionsGet200ResponseProcessingInformationAuthorizationOptionsInitiator } from './tss-v2-transactions-get200-response-processing-information-authorization-options-initiator';
/**
 * 
 * @export
 * @interface TssV2TransactionsGet200ResponseProcessingInformationAuthorizationOptions
 */
export interface TssV2TransactionsGet200ResponseProcessingInformationAuthorizationOptions {
    /**
     * Authorization type. Possible values:   - `AUTOCAPTURE`: automatic capture.  - `STANDARDCAPTURE`: standard capture.  - `VERBAL`: forced capture. Include it in the payment request for a forced capture. Include it in the capture request for a verbal payment.  #### Asia, Middle East, and Africa Gateway; Cielo; Comercio Latino; and CyberSource Latin American Processing Set this field to `AUTOCAPTURE` and include it in a bundled request to indicate that you are requesting an automatic capture. If your account is configured to enable automatic captures, set this field to `STANDARDCAPTURE` and include it in a standard authorization or bundled request to indicate that you are overriding an automatic capture. For more information, see the `auth_type` field description in [Credit Card Services Using the SCMP API Guide.](https://apps.cybersource.com/library/documentation/dev_guides/CC_Svcs_SCMP_API/html/)  #### Forced Capture Set this field to `VERBAL` and include it in the authorization request to indicate that you are performing a forced capture; therefore, you receive the authorization code outside the CyberSource system.  #### Verbal Authorization Set this field to `VERBAL` and include it in the capture request to indicate that the request is for a verbal authorization. For more information, see \"Verbal Authorizations\" in [Credit Card Services Using the SCMP API](http://apps.cybersource.com/library/documentation/dev_guides/CC_Svcs_SCMP_API/html). 
     * @type {string}
     * @memberof TssV2TransactionsGet200ResponseProcessingInformationAuthorizationOptions
     */
    authType?: string;
    /**
     * 
     * @type {TssV2TransactionsGet200ResponseProcessingInformationAuthorizationOptionsInitiator}
     * @memberof TssV2TransactionsGet200ResponseProcessingInformationAuthorizationOptions
     */
    initiator?: TssV2TransactionsGet200ResponseProcessingInformationAuthorizationOptionsInitiator;
}
