/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TssV2TransactionsPost201ResponseEmbeddedClientReferenceInformationPartner
 */
export interface TssV2TransactionsPost201ResponseEmbeddedClientReferenceInformationPartner {
    /**
     * Identifier for the partner that is integrated to CyberSource.  Send this value in all requests that are sent through the partner solution. CyberSource assigns the ID to the partner.  **Note** When you see a solutionId of 999 in reports, the solutionId that was submitted is incorrect. 
     * @type {string}
     * @memberof TssV2TransactionsPost201ResponseEmbeddedClientReferenceInformationPartner
     */
    solutionId?: string;
}
