/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TssV2TransactionsGet200ResponseRiskInformationScore
 */
export interface TssV2TransactionsGet200ResponseRiskInformationScore {
    /**
     * Array of factor codes.
     * @type {Array<string>}
     * @memberof TssV2TransactionsGet200ResponseRiskInformationScore
     */
    factorCodes?: Array<string>;
    /**
     * The description for this field is not available. 
     * @type {number}
     * @memberof TssV2TransactionsGet200ResponseRiskInformationScore
     */
    result?: number;
}
