/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TssV2TransactionsPost201ResponseEmbeddedProcessorInformationProcessor
 */
export interface TssV2TransactionsPost201ResponseEmbeddedProcessorInformationProcessor {
    /**
     * Name of the Processor. 
     * @type {string}
     * @memberof TssV2TransactionsPost201ResponseEmbeddedProcessorInformationProcessor
     */
    name?: string;
}
