/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TssV2TransactionsPost201ResponseEmbeddedRiskInformationProviders } from './tss-v2-transactions-post201-response-embedded-risk-information-providers';
/**
 * 
 * @export
 * @interface TssV2TransactionsPost201ResponseEmbeddedRiskInformation
 */
export interface TssV2TransactionsPost201ResponseEmbeddedRiskInformation {
    /**
     * 
     * @type {TssV2TransactionsPost201ResponseEmbeddedRiskInformationProviders}
     * @memberof TssV2TransactionsPost201ResponseEmbeddedRiskInformation
     */
    providers?: TssV2TransactionsPost201ResponseEmbeddedRiskInformationProviders;
}
