/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TssV2TransactionsPost201ResponseEmbeddedOrderInformationShipTo
 */
export interface TssV2TransactionsPost201ResponseEmbeddedOrderInformationShipTo {
    /**
     * First name of the recipient.  #### Litle Maximum length: 25  #### All other processors Maximum length: 60  Optional field. 
     * @type {string}
     * @memberof TssV2TransactionsPost201ResponseEmbeddedOrderInformationShipTo
     */
    firstName?: string;
    /**
     * Last name of the recipient.  #### Litle Maximum length: 25  #### All other processors Maximum length: 60  Optional field. 
     * @type {string}
     * @memberof TssV2TransactionsPost201ResponseEmbeddedOrderInformationShipTo
     */
    lastName?: string;
    /**
     * First line of the shipping address.  Required field for authorization if any shipping address information is included in the request; otherwise, optional.  #### Tax Calculation Optional field for U.S. and Canadian taxes. Not applicable to international and value added taxes. Billing address objects will be used to determine the cardholder’s location when shipTo objects are not present. 
     * @type {string}
     * @memberof TssV2TransactionsPost201ResponseEmbeddedOrderInformationShipTo
     */
    address1?: string;
    /**
     * Country of the shipping address. Use the two-character [ISO Standard Country Codes.](http://apps.cybersource.com/library/documentation/sbc/quickref/countries_alpha_list.pdf)  Required field for authorization if any shipping address information is included in the request; otherwise, optional.  #### Tax Calculation Optional field for U.S., Canadian, international tax, and value added taxes. Billing address objects will be used to determine the cardholder’s location when shipTo objects are not present. 
     * @type {string}
     * @memberof TssV2TransactionsPost201ResponseEmbeddedOrderInformationShipTo
     */
    country?: string;
    /**
     * Phone number associated with the shipping address.
     * @type {string}
     * @memberof TssV2TransactionsPost201ResponseEmbeddedOrderInformationShipTo
     */
    phoneNumber?: string;
}
