/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TssV2TransactionsGet200ResponseInstallmentInformation
 */
export interface TssV2TransactionsGet200ResponseInstallmentInformation {
    /**
     * Number of Installments.
     * @type {string}
     * @memberof TssV2TransactionsGet200ResponseInstallmentInformation
     */
    numberOfInstallments?: string;
    /**
     * Standing Instruction/Installment identifier. 
     * @type {string}
     * @memberof TssV2TransactionsGet200ResponseInstallmentInformation
     */
    identifier?: string;
}
