/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TssV2TransactionsGet200ResponseProcessorInformationAchVerification
 */
export interface TssV2TransactionsGet200ResponseProcessorInformationAchVerification {
    /**
     * Results from the ACH verification service. For details about this service and the possible values for the results, see \"ACH Verification\" and \"Verification Codes\" in the [Electronic Check Services Using the SCMP API](https://apps.cybersource.com/library/documentation/dev_guides/EChecks_SCMP_API/html/). 
     * @type {string}
     * @memberof TssV2TransactionsGet200ResponseProcessorInformationAchVerification
     */
    resultCode?: string;
    /**
     * Raw results from the ACH verification service. For details about this service and the possible values for the raw results, see \"ACH Verification\" and \"Verification Codes\" in the [Electronic Check Services Using the SCMP API](https://apps.cybersource.com/library/documentation/dev_guides/EChecks_SCMP_API/html/). 
     * @type {string}
     * @memberof TssV2TransactionsGet200ResponseProcessorInformationAchVerification
     */
    resultCodeRaw?: string;
}
