/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Riskv1liststypeentriesBuyerInformation } from './riskv1liststypeentries-buyer-information';
import { Riskv1liststypeentriesClientReferenceInformation } from './riskv1liststypeentries-client-reference-information';
import { Riskv1liststypeentriesDeviceInformation } from './riskv1liststypeentries-device-information';
import { Riskv1liststypeentriesOrderInformation } from './riskv1liststypeentries-order-information';
import { Riskv1liststypeentriesPaymentInformation } from './riskv1liststypeentries-payment-information';
import { Riskv1liststypeentriesRiskInformation } from './riskv1liststypeentries-risk-information';
/**
 * 
 * @export
 * @interface TypeEntriesBody
 */
export interface TypeEntriesBody {
    /**
     * 
     * @type {Riskv1liststypeentriesOrderInformation}
     * @memberof TypeEntriesBody
     */
    orderInformation?: Riskv1liststypeentriesOrderInformation;
    /**
     * 
     * @type {Riskv1liststypeentriesPaymentInformation}
     * @memberof TypeEntriesBody
     */
    paymentInformation?: Riskv1liststypeentriesPaymentInformation;
    /**
     * 
     * @type {Riskv1liststypeentriesClientReferenceInformation}
     * @memberof TypeEntriesBody
     */
    clientReferenceInformation?: Riskv1liststypeentriesClientReferenceInformation;
    /**
     * 
     * @type {Riskv1liststypeentriesDeviceInformation}
     * @memberof TypeEntriesBody
     */
    deviceInformation?: Riskv1liststypeentriesDeviceInformation;
    /**
     * 
     * @type {Riskv1liststypeentriesRiskInformation}
     * @memberof TypeEntriesBody
     */
    riskInformation?: Riskv1liststypeentriesRiskInformation;
    /**
     * 
     * @type {Riskv1liststypeentriesBuyerInformation}
     * @memberof TypeEntriesBody
     */
    buyerInformation?: Riskv1liststypeentriesBuyerInformation;
}
