/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { V1FileDetailsGet200ResponseFileDetails } from './v1-file-details-get200-response-file-details';
import { V1FileDetailsGet200ResponseLinks } from './v1-file-details-get200-response-links';
/**
 * 
 * @export
 * @interface V1FileDetailsGet200Response
 */
export interface V1FileDetailsGet200Response {
    /**
     * 
     * @type {Array<V1FileDetailsGet200ResponseFileDetails>}
     * @memberof V1FileDetailsGet200Response
     */
    fileDetails?: Array<V1FileDetailsGet200ResponseFileDetails>;
    /**
     * 
     * @type {V1FileDetailsGet200ResponseLinks}
     * @memberof V1FileDetailsGet200Response
     */
    links?: V1FileDetailsGet200ResponseLinks;
}
