/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface V1FileDetailsGet200Response
 */
export interface V1FileDetailsGet200Response {
    /**
     * 
     * @type {Array<any>}
     * @memberof V1FileDetailsGet200Response
     */
    fileDetails?: Array<any>;
    /**
     * 
     * @type {any}
     * @memberof V1FileDetailsGet200Response
     */
    links?: any;
}
