/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Kmsv2keysasymKeyInformation } from './kmsv2keysasym-key-information';
import { Kmsv2keyssymClientReferenceInformation } from './kmsv2keyssym-client-reference-information';
/**
 * 
 * @export
 * @interface V2KeysasymBody
 */
export interface V2KeysasymBody {
    /**
     * 
     * @type {Kmsv2keyssymClientReferenceInformation}
     * @memberof V2KeysasymBody
     */
    clientReferenceInformation?: Kmsv2keyssymClientReferenceInformation;
    /**
     * 
     * @type {Array<Kmsv2keysasymKeyInformation>}
     * @memberof V2KeysasymBody
     */
    keyInformation?: Array<Kmsv2keysasymKeyInformation>;
}
