/* tslint:disable */
/* eslint-disable */
/**
 * CyberSource Merged Spec
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Reportingv3reportsReportFilters } from './reportingv3reports-report-filters';
import { Reportingv3reportsReportPreferences } from './reportingv3reports-report-preferences';
/**
 * 
 * @export
 * @interface V3ReportsBody
 */
export interface V3ReportsBody {
    /**
     * Valid CyberSource Organization Id
     * @type {string}
     * @memberof V3ReportsBody
     */
    organizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof V3ReportsBody
     */
    reportDefinitionName?: string;
    /**
     * List of fields which needs to get included in a report
     * @type {Array<string>}
     * @memberof V3ReportsBody
     */
    reportFields?: Array<string>;
    /**
     * 'Format of the report'                  Valid values: - application/xml - text/csv 
     * @type {string}
     * @memberof V3ReportsBody
     */
    reportMimeType?: string;
    /**
     * Name of the report
     * @type {string}
     * @memberof V3ReportsBody
     */
    reportName?: string;
    /**
     * Timezone of the report
     * @type {string}
     * @memberof V3ReportsBody
     */
    timezone?: string;
    /**
     * Start time of the report
     * @type {Date}
     * @memberof V3ReportsBody
     */
    reportStartTime?: Date;
    /**
     * End time of the report
     * @type {Date}
     * @memberof V3ReportsBody
     */
    reportEndTime?: Date;
    /**
     * 
     * @type {Reportingv3reportsReportFilters}
     * @memberof V3ReportsBody
     */
    reportFilters?: Reportingv3reportsReportFilters;
    /**
     * 
     * @type {Reportingv3reportsReportPreferences}
     * @memberof V3ReportsBody
     */
    reportPreferences?: Reportingv3reportsReportPreferences;
    /**
     * Specifies the group name
     * @type {string}
     * @memberof V3ReportsBody
     */
    groupName?: string;
}
